### ISSUE TITLE
Gboard keyboard hides the description field while editing TE

### ISSUE THREAD

**Issue by nidarasheed** [toggl/mobileapp#6070] opened 2019-10-09 08:20 UTC
## 🐛 Bug Report

The custom keyboard, Gboard, hides the description field while editing. This does not happen with the stock iPhone keyboard. 

## Context

Build/Branch: Daneel 2.4
Phone OS: 13.1.2
Phone model: iPhone 8 

## Expected behavior

The user should be able to see the description they are typing in. 
## To reproduce

- Install gboard
- Open Toggl  
- Click on a TE to edit
- Try and enter description 
![image](https://user-images.githubusercontent.com/49634673/66463811-43cd4c80-ea97-11e9-839a-51150d786030.png)

## Suggestions

[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24008003165)

**Comment by simonrozsival** [comment] 2019-11-11 09:41
We might need to do something like they suggest in https://stackoverflow.com/questions/39066206/ios-gboard-app-uikeyboard-notification-height-is-wrong-or-invalid

**Comment by simonrozsival** [comment] 2019-11-12 11:42
I cannot reproduce this with iOS 13, iPhone 7. I believe we fixed this in 2.6.1 with #6471. I'm closing this issue now.

**Closed by simonrozsival** 2019-11-12 11:42 UTC
Labels: glitch, ios
