### ISSUE TITLE
Start time entry button does not appear

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2482] opened 2018-06-18 09:45 UTC
Repro steps:

- Fresh install from App Store
- Login (using PW manager, not that it matters)
- Turned connection off after login succeeds

The start time entry button did not appear. Restarting made it work and I could not reproduce since. FWIW, I think we should investigate the relationship between our observable lifecycle vs the internet connection dropping suddenly.

<sub>This is a bug and not a glitch, since it effectivelly makes it impossible for people to create new TEs without resetting, which is gross and gives the impression that the app does not work</sub>

**Comment by simonrozsival** [comment] 2018-06-25 10:28
I can't reproduce this bug. How do you turn off connection between the login suceeds and before the button normally appears - it is a fraction of seconds.

**Comment by simonrozsival** [comment] 2018-06-28 16:14
Fix was merged into a release branch.

**Closed by simonrozsival** 2018-06-28 16:14 UTC
Labels: bug, ios, pending-review
