### ISSUE TITLE
Cannot stop or edit an entry after starting it on the app and syncing 1.5 (1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2148] opened 2018-05-16 02:57 UTC
(V1.5(1284))
Continued a time entry.
App synced
Attempted to stop entry.
Stop button was greyed out.
Attempted to stop again
App crashes.

![syncissue2](https://user-images.githubusercontent.com/18132080/40094149-7fc9db02-5904-11e8-8a99-eaf76a2a0dbb.gif)

**Comment by ApocalypticFish** [comment] 2018-05-16 03:07
Tested this with starting an entry and also cannot. Have to force close the app and re-open it for the entry to show that it has stopped.

**Comment by ApocalypticFish** [comment] 2018-05-16 06:01
The same behaviour happens when trying to edit the entry after starting it. 
After the crash, it can be edited.

**Comment by ApocalypticFish** [comment] 2018-05-16 06:38
Also crashes when attempting to edit recently created manual entry

**Comment by sofokli1** [comment] 2018-07-09 18:42
Can't reproduce on develop neither on app store. The issue seems a bit old. If no one can reproduce it I vote to close this.

**Closed** 2018-07-16 14:13 UTC
Labels: crash, ios
