### ISSUE TITLE
Index was out of range in SelectProjectRecyclerAdapter.GetItem

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4114] opened 2019-01-07 15:45 UTC
## 💥 Crash Report
Didn't replicate it yet but the crash happens in SelectProjectRecyclerAdapter which is only used in the SelectProjectRecyclerView inside the SelectProjectActivity, which is only used when editing time entries.

### 👥 Impact
It's the most common crash in 1.9, accounting for 849 (15.1% of all crashes) and affecting 369 users so far.

### 🔗 Context
The views involved are not rxfactored yet, so keep in mind that whatever you write is temporary.
This crash should go away on it's own when #4012 is done, but I don't think it's worth waiting.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3717584108u/overview

### 📝  Exception & Stack Trace
Not very helpful this time but:
`Exception type and message`
```cs
List`1[T].get_Item (System.Int32 index)
Collection`1[T].get_Item (System.Int32 index)
SelectProjectRecyclerAdapter.GetItem (System.Int32 viewPosition)
MvxRecyclerAdapter.GetItemViewType (System.Int32 position)
RecyclerView+Adapter.n_GetItemViewType_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position)
(wrapper dynamic-method) System.Object.41(intptr,intptr,int)
```

**Comment by daividssilverio** [comment] 2019-01-07 22:43
I investigated... couldn't replicate the exact crash but got to crash the app very easily by scrolling and then typing something in the search box int he Select Project view...
Tried to put a lock around places where the collection is read (`GetItem`) and in the adapter is notified about changes, but it didn't work.

Not sure what caused these crashes to emerge... still under investigation.
We might end up wanting to wait for #4012... it's hard to work with the `SegmentedRecyclerAdapter` and `NestableObservableCollection`... that's why the `ObservableGroupedOrderedCollection` and `ReactiveSectionedRecyclerAdapter` came to be.

**Comment by daividssilverio** [comment] 2019-01-08 16:01
The only changes related to the crash from 1.7 to 1.9 affect these lines:
https://github.com/toggl/mobileapp/blob/b1e45836300d04d257dd016460c7ae94f2b3f05d/Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs#L149-L157
and
https://github.com/toggl/mobileapp/blob/b1e45836300d04d257dd016460c7ae94f2b3f05d/Toggl.Giskard/Adapters/SelectProjectRecyclerAdapter.cs#L37-L46

I tracked down crashes (not exactly the same in the report, but related) to source from these two lines:
https://github.com/toggl/mobileapp/blob/b1e45836300d04d257dd016460c7ae94f2b3f05d/Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs#L152
and
https://github.com/toggl/mobileapp/blob/b1e45836300d04d257dd016460c7ae94f2b3f05d/Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs#L154

Removing them seems to stop the crashes (or at least reduce it) on Android (iOS isn't affected), but it makes the view slower for everybody, so it doesn't look like a good idea.
I'll move this issue to 1.11 and it should go away when #4012 is done, which started being worked on anyway.

**Comment by juanlaube** [comment] 2019-01-10 18:30
I tried to reproduce this, but so far I couldn't.

**Comment by daividssilverio** [comment] 2019-01-10 18:38
Try scrolling and typing at the same time.

**Comment by juanlaube** [comment] 2019-01-11 17:09
@daividssilverio even doing that, I can't still reproduce this, any ideas?

**Comment by arturs105** [comment] 2019-03-05 16:14
I think i may know how to replicate this exception. Or at least an exception in the same method. I am working on a UI test that tries to change a project of a time entry that has a project (part of #4445) and that test fails 90% of the time.

#### Steps executed in the test:
1. Register with a fresh account
2. Create a project `project1` (this is done by starting a time entry, creating a new project from the start time entry view and then discarding the time entry)
3. Start a time entry with some description and assign a new project `project2`
4. Stop that time entry
5. Tap on the time entry in the log
6. Tap on the project row in the edit time entry view
7. Enter the name of the first project `project1`
8. Tap on `project1` to select it

After repeating this test manually several times, i found that the app crashes somewhere around step 7 or 8. Also found that this does not happen 100% of the time, so you may need to repeat steps 6 - 8 a few times. Last note: it even crashed when i skipped step 7, so that is worth trying as well. In short: try switching between the 2 projects and the crash should reveal itself 👻 .

After getting the exception, the execution paused and i was able to inspect some variables. I suspect that `IsSuggestingCreation` may have something do with the crash, because it was `true` at the time of the crash, even there was no filter text entered and the recycler view didn't have the "Create project" cell.

**Comment by amulware** [comment] 2019-03-22 10:51
The grouped time entry project should be merged soon. Let's review this then and see if it still happens or not.

**Comment by kornelijepetak** [comment] 2019-03-25 05:41
@amulware this will not be solved by GTE per se, but by #4562. However, I agree that testing makes sense after the GTE branch is in develop so that we are sure it didn't at least introduce any new problems.

**Comment by kornelijepetak** [comment] 2019-03-29 13:10
Unfortunatelly, I must confirm that this is still occasionally happening on `develop` after both #4562 and #4353 were merged into `develop`.

I will investigate more and try to fix it at some point.

**Comment by kornelijepetak** [comment] 2019-04-23 09:19
Ok, I'm finally closing this issue. 

There are more than 52% of the users on 1.12+ and there was not a single crash like this since that update.

My observed crash may have been a fluke and since it wasn't in the debug, I can't guarantee that it wasn't just another type of similar crash.

If we notice this crash again in versions > 1.12, we'll reopen the issue.

**Closed by kornelijepetak** 2019-04-23 09:19 UTC
Labels: android, crash, on-hold
