### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by gavinfernandes2012** [toggl/mobileapp#3588] opened 2018-10-30 08:50 UTC
## 🐛 Bug Report
When using a proxy, the app does not respect the system's proxy settings

## Context
When using manual proxy settings for a wifi network in android, the app does not respect the proxy settings.

Build/Branch: The latest from the play store
Phone OS: Android 9.0 Pie
Phone model: Essential Ph-1

## Expected behavior
The app should direct its traffic through the proxy.

## To reproduce
Set up a manual proxy in android's wifi settings. The app does not route its traffic through the proxy.

## Suggestions
[This](https://forums.xamarin.com/discussion/7315/android-proxy-settings) link might help.

**Comment by juanlaube** [comment] 2018-10-30 11:03
Hi @gavinfernandes2012, thanks for the bug report.

Adding up to this issue, I can confirm this is also a problem in iOS.

Build/Branch: Daneel 1.12.1 from AppStore
Phone OS: iOS
Phone model:

**Comment by simonrozsival** [comment] 2018-11-06 17:04
An implementation was merged into `develop` - it should be part of the `1.14` iOS release and `1.7` Android release. The exact dates for these releases are not known yet but it should be no more than two to three weeks from now. No promises though 😄 You can check our progress in the `Projects` tab.

Please let us know if it works well in your case, @gavinfernandes2012, once we release it and you update to that version. Thanks for reporting the issue to us again!

**Comment by arturs105** [comment] 2018-11-07 16:14
Reopening because this introduced some SSL errors that made it impossible to do any web requests to Toggl api.

This issue can be closed once the SSL errors are solved.

**Closed** 2020-01-02 16:37 UTC
Labels: api

**Comment by simonrozsival** [comment] 2020-01-02 19:01
This feature should be finally released in the next release. The problems we had last time (problems with the self-signed Toggl staging certificate) are resolved and therefore there shouldn't be any reason to roll it back this time.
