### ISSUE TITLE
Problem with date and time formats

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1721] opened 2018-03-14 18:19 UTC
*I'm currently using TF build 1.4 (28) which should be the same as the one that is currently up in the App Store.*

When edit running or existing TE, then date/time formats are messed up. Check the screenshot below:

![image uploaded from ios](https://user-images.githubusercontent.com/5064445/37422791-14835b58-278a-11e8-9540-0958a06bbe1a.png)

Also, when I open settings to check out what happens there, then date format is "missing" (nothing isn't selected) and 24-hour format is turned off, though I haven't turned it off. When I turn 24-format back on, then all is good again. Though, the issue appears again when i restart the app.

![image uploaded from ios 1](https://user-images.githubusercontent.com/5064445/37422803-1d3d1450-278a-11e8-8a12-292cb10d8b41.png)

That's the best way how can I describe the issue. Ping me for more questions.

**Comment by pe0ny** [comment] 2018-03-14 18:26
Also happens on 1.4.1 (29)

**Comment by simonrozsival** [comment] 2018-03-14 18:49
I also noticed it and I think I know what the problem is. I will look into this tomorrow morning.

**Comment by simonrozsival** [comment] 2018-03-27 08:04
This was already merged into 1.4.2 which was already released.

**Closed by simonrozsival** 2018-03-27 08:04 UTC
Labels: bug, ios, pending-review
