### ISSUE TITLE
Emtpy Suggestion on Android

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5510] opened 2019-06-28 20:12 UTC
While testing the suggestions directly from the suggestions branch, I've got an empty suggestion.

It looks like an error to see an empty suggestion like this; and when I asked on slack, I was told this wasn't supposed to be like this.

While debugging, just for reference, the Item description is empty, this isn't a glitch. The suggestion is empty. Here's a screenshot for reference:

![suggestions](https://user-images.githubusercontent.com/2173493/60368832-e9185500-99bf-11e9-924b-22c320c686be.png)

**Comment by kornelijepetak** [comment] 2019-07-02 15:41
It's unclear to me how it comes to the empty suggestion. Particulary since the suggestion seems to be empty itself, and not a UI glitch.

We are using three providers

1. Most used provider - does not even look at TEs without description. It does allow no description though if there's a project available, so there's a small chance of the project name being just whitespace (albeit this is not allowed by mobile and webapp so not sure how that's possible)
2. Calendar provider - ignores all empty (albeit not only-whitespace) calendar entries. 
3. ML provider - ignores description altogether when determining which TEs to take, but choses ONLY TEs that do have a project. So in that case, a project would be shown in suggestion, unless it's for some reason whitespace (as in 2.).

And since in debug the suggestion does not show the first 4 letters of a provider, it means that it's hidden, which in turn means that the description in suggestion is really an empty string or whitespace.

In #5514, I've added a check to make sure that all string comparisons treat whitespace-only strings the same way as truly empty ones. 

Whether this is enough to solve this issue, it's questionable.

But because I'm not able to reproduce this bug (or even understand from code how this is even possible), for now, I propose this be moved out of the suggestions project into a normal issue and be solved when we gather more about the problem, and also after we see that indeed it happens again after #5514.

**Comment by kornelijepetak** [comment] 2019-07-02 15:51
After discussing this with @daividssilverio, it seems that #5514 did fix things for his use case, so I'm closing this issue instead. For the time being. If we notice similar behaviour again, we'll reopen it.

**Closed by kornelijepetak** 2019-07-02 15:51 UTC
