### ISSUE TITLE
Time entries from other workspace aren't displayed when the user log in

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2451] opened 2018-06-13 07:00 UTC
It was reported that after log in, only TEs from the default WS are displayed, though we should display TEs across all the WSs.
Atm it requires manual sync to see TE from other WSs.

Can someone reproduce it? In my case, the app downloads TEs from all the workspaces right after the log in.

**Comment by khoi** [comment] 2018-06-13 07:01
<img width="427" alt="screen shot 2018-06-13 at 13 26 44" src="https://user-images.githubusercontent.com/6994441/41335225-42d70462-6f12-11e8-9045-548c817a2667.png">

**Comment by amulware** [comment] 2018-06-13 07:06
This makes absolutely no sense at all with how our sync works.

@khoi What happens if you:
- sign in (only shows from one workspace)
- **go offline** (to prevent further syncing)
- try to sync (does it show the other data?)
- try to restart the app (does it show the other data?)

**Comment by kornelijepetak** [comment] 2018-06-13 07:07
I have also checked some code, it seems that there is no filtering by workspace happening anywhere in this process...

**Comment by khoi** [comment] 2018-06-13 07:08
>- Go offline, try to sync
I got Offline message and it doesn't show TE from other workspaces.
>- Restart the app
Restart the app with network works. All the TEs are displayed

**Comment by amulware** [comment] 2018-06-13 07:19
This seems to have broken recently (appstore build is still fine), which makes me think it might be related to the new endpoint we use to download 2 months worth of data.

**Comment by pe0ny** [comment] 2018-06-13 08:12
Yes, I tested the app store build and it was ok.

**Comment by amulware** [comment] 2018-06-13 09:05
I confirmed that the new endpoint (see https://github.com/toggl/backend/issues/6110) should return TEs from all workspaces.

This needs a detailed investigation to figure out if the bug is on our side or on backend's.

We can't release a build without figuring this out, so I'm marking this as blocking.

**Comment by daividssilverio** [comment] 2018-06-14 00:31
I did a small test debugging the the api calls and the persisting order.
It turns out that for some reason, the time entries are not being persisted on the first try (right after login), but only after a manual sync.

**Comment by daividssilverio** [comment] 2018-06-15 13:38
My previous comment cannot be reproduced anymore. I don't know what did I do to make it happen.

**Comment by daividssilverio** [comment] 2018-06-15 13:50
As for the problem, it seems that the way we are using the api to do the initial sync pull is not including all the time entries, depending on what time you try to do it.

We talked to the backend guys, and the endpoint: `/api/v9/me/time_entries?start_date=2018-04-14&end_date=2018-06-14` is inclusive to `end_date` parameter, but to the millisecond level, so in the end, it won't return time entries created in the `end_date`.

To use the endpoint properly, we will have to add +2 days to `end_date` (1 to include the end_date we actually want, and +1 because of timezones). At least for now.

**Closed** 2018-06-19 12:52 UTC
Labels: blocking, bug, pending-review, sync
