### ISSUE TITLE
iPad: Main log not resizing correctly for 1/3 size on iPad 12"

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4954] opened 2019-04-19 08:29 UTC
## 🐛 Bug Report
When resizing to 1/3 the main log view does not resize correctly. it extends beyond the left and right bounds.

## Context
Build/Branch: project/ipad
Phone OS: ios
Phone model: ipad 12" (maybe other ipads too didn't check.

## Expected behavior
To resize correctly and look like the phone main log

## To reproduce
run on the simulator and split screen until you reach 1/3 size

## Suggestions
maybe auto layout

 
![Simulator Screen Shot - iPad Pro (12 9-inch) - 2019-04-19 at 11 25 50](https://user-images.githubusercontent.com/885122/56417748-8eff6300-629d-11e9-87ee-09f57bfe8c74.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) - 2019-04-19 at 11 24 09](https://user-images.githubusercontent.com/885122/56417749-8eff6300-629d-11e9-8258-d41dab5cf8a5.png)

**Comment by amulware** [comment] 2019-05-15 09:38
On second thought, this actually seems pretty severe.

**Comment by dshr** [comment] 2019-05-15 10:38
@amulware indeed, but the problem is that we couldn’t reproduce a second time in a prod build, and haven’t heard any reports of it happening in the wild.

**Comment by amulware** [comment] 2019-05-17 12:37
In which case we should maybe close it. Or maybe @sofokli1 has an idea or knows what's up when he's back next week.

**Comment by sofokli1** [comment] 2019-05-23 09:46
I suggest to wait for people to complain before doing something since it is not very consistent to reproduce.

**Closed** 2019-05-29 09:41 UTC
Labels: bug, ios
