### ISSUE TITLE
Figure out symbol files for Siri extension

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4189] opened 2019-01-14 10:57 UTC
There are unsymbolicated crashes, we have to figure out how to get these symbols to AppCenter.

Right now it's 'only' Siri, but down the line, we might have a whole set of extensions!

**Comment by juanlaube** [comment] 2019-09-26 12:42
This is not currently supported by the `xamarin-archive` step in bitrise, I did some research and found it only picks the `*.app.dSYM` file, ignoring all the `*.appex.dSYM` we want.
I created [an issue]( https://github.com/bitrise-steplib/steps-xamarin-archive/issues/37) asking if it's in their plans, we could also contribute and do it ourselves, because it looks really simple.

**Comment by juanlaube** [comment] 2019-09-26 12:46
We could also do this with a ✨  shell script ✨ , but I'd rather not do that, it's much better to have this in the `xamarin-archive` step.

**Comment by juanlaube** [comment] 2019-09-26 13:59
ping @amulware to decide what to do next ☝️

**Comment by amulware** [comment] 2019-09-26 15:56
I fully support to get Bitrise to change their step, or help them do it. That looks like a lot less effort than anything we could do on our side.

**Comment by amulware** [comment] 2019-09-26 15:57
Should we mention in the issue you created that we'd be happy to help?

**Comment by juanlaube** [comment] 2019-09-26 15:59
Yes, I will do that 😄

**Comment by juanlaube** [comment] 2019-10-22 18:49
Bitrise confirmed [in this issue](https://github.com/bitrise-steplib/steps-xamarin-archive/issues/37) this is not on their short terms plans but they are open to contributions. I can try to do this, can we allocate some time in the next weeks @amulware?

**Comment by amulware** [comment] 2019-10-23 15:53
If we think it's worth it, yes we absolutely can. It's scheduled afterall, and I don't care if we fix it in our repo or in theirs. :D (Assuming the effort involved is not very large.)

**Comment by heytherewill** [comment] 2019-11-18 19:02
I took a quick look at this, but apparently it's not as simple as changing the regex to make a match. Since I will be looking into bitrise steps again in Android 2.9, I vote we move this to 2.9 so I writing Go becomes future Will's responsibility and I can do it all at once

**Comment by simonrozsival** [comment] 2019-12-31 13:38
@heytherewill won't be able to finish this in time for 2.9, so I'm unasigning him from this issue now.

**Comment by juanlaube** [comment] 2020-01-23 16:23
We have been moving this issue around for some time now, lets tackle this in the 2.12 release.
Instead of modifying the existing bitrise step, we should create our own step to solve our problem, this should be easier to implement and deploy.
The guidelines to create our own steps can be found here https://devcenter.bitrise.io/contributors/create-your-own-step/

**Closed** 2020-02-11 16:04 UTC
Labels: ios, xamarin-sunset
