### ISSUE TITLE
Test rate-us view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2620] opened 2018-07-06 14:25 UTC
We need to verify that:

- [x] the remote config works as expected
- [x] the rate-us view pops up based on the remote config as specified
- [x] all four paths have the expected outcome
- [ ] it behaves correctly if the user ignores it and leaves the app for short/longer durations
- [x] the final state is store correctly, and the view is never shown again
- [ ] metrics events are being sent off

I'd also like someone to figure out how @pe0ny and @ApocalypticFish to test the UX side of this without having to dig into the code.

**Comment by sofokli1** [comment] 2018-07-12 12:46
- For the UX part I would propose a branch fixed in a way that always shows the rating view.
- For the rest I would propose to set up everything the same way as in app store app id but for develop and adhoc. Everything will be separate by app id (analytics crashes etc.) so no noise from the development app id in the app store one. This way we can play with a/b testing in develop and adhoc (bitrise) and in the end just copy the experiment in the app store app id. (same goes for testing new analytics events and what not)

**Comment by amulware** [comment] 2018-07-13 09:45
Do we then need a separate configuration in firebase/app center? I'm pretty sure those are tied to app id.

**Comment by sofokli1** [comment] 2018-07-13 09:49
I don't think so. I think it is enough to just remove the` #if` in the appDelegate

**Comment by amulware** [comment] 2018-07-13 10:40
Let's do it then.

**Comment by sofokli1** [comment] 2018-07-13 15:42
@amulware For the firebase we need at least the googl-app-id and some other keys for appCenter and facebook that it is usually only set in bitrise. I would suggest to have 3 scripts. 1 shared only internally to set the env variable in our local machines and 2 scripts (or one with parameters) to set and unset the values from project (set values before build and unset after build automatically). So the varaibels will be set and unset without affecting git. Does this make sense? Should i move forward with this?

**Comment by amulware** [comment] 2018-07-13 15:44
Why not just build a test build on bitrise to replace secrets? And I'm not sure of the exact state, but what about Arturs' test branch? (Ricardo mentioned it earlier)

**Comment by sofokli1** [comment] 2018-07-13 15:46
I would start only with the google/firebase thing and then see about appCenter and facebook in a different PR based on needs

**Comment by sofokli1** [comment] 2018-07-16 16:37
My main issues with the rating view and the firebase remote config (a/b testing) are:
- When there is an error fetching the configuration, It is not handled and it will crash. (at least on the branch for testing)
- If the view is presented and the app restarts the view will not show up again even if the users never interacted with it (not sure if this is by design).

- It is hard to test if the metrics events are sent to firebase since it takes around 24 h for them to appear.


Will make an other comment with details steps and screenshots on how to setup experiments using test devices and how to always show the rating view for testing purposes.

**Comment by amulware** [comment] 2018-07-17 10:57
The events should be sent to app center as well - maybe that has more-live data? Not as good as testing the proper thing though I guess.

**Comment by sofokli1** [comment] 2018-07-17 18:55
The following steps can be used in other a/b testing cases with some changes.

# Test/debug A/B testing from firebase to your device
## Preparations
1. I assume visual studio for mac is installed and the project ready to go and able to install on device.
2. Switch to the branch `rating-view-test`
To be sure check if the `Solution` pad is showing the branch name as below
![screen shot 2018-07-17 at 19 16 06](https://user-images.githubusercontent.com/885122/42831114-2a402402-89f6-11e8-9ae2-b65274981fa3.png)
3. Go to [Firebase Console](https://console.firebase.google.com)
Make sure you are logged in with the correct google account in the right upper corner and select `Toggle Mobile`
Once in you should follow the 4 steps as shown in the screenshot below to download the configuration file for firebase
![screen shot 2018-07-17 at 19 22 04](https://user-images.githubusercontent.com/885122/42831711-bee5692c-89f7-11e8-87f6-59f85b23dec9.png)
If there is any issues with downloading the file contact mobile team.
4. Replace the file in the project with the newly downloaded one. Just right click the file in the `Solution` pad and select `Reveal in Finder`. There just replace it with the newly downloaded one.
![screen shot 2018-07-17 at 19 31 29](https://user-images.githubusercontent.com/885122/42831904-495bc1f0-89f8-11e8-8371-eb2e2c1fbc8f.png)
5. Connect your device to the laptop and make sure the configuration on the top is set like below (but with your device name.
![screen shot 2018-07-17 at 19 34 51](https://user-images.githubusercontent.com/885122/42832065-b9660e74-89f8-11e8-910d-732b4da54c75.png)
6. We just need to add `USE_ANALYTICS;` in the project configuration as shown in the screenshot below
![screen shot 2018-07-17 at 19 38 27](https://user-images.githubusercontent.com/885122/42832438-ddd1fb46-89f9-11e8-84c9-1e65d2cb7747.png)
7. Run the app by pressing the play button on the top left corner of visual studio for mac.
If there is any issues try running `sh build.sh` in terminal in the same folder as the project.
If there still is a problem running the app contact mobile team.
If everything works fine you should see something like this after logging in the device (with the same values in the pop up)
![screen shot 2018-07-17 at 20 59 29](https://user-images.githubusercontent.com/885122/42839029-0ca7dde4-8a0b-11e8-9651-37529d0402bf.png)


## A/B Test creation
1. Run the app and go to `Settings > Export Firebase Token` choose a way to share it with yourself for copy and paste purposes later on. **If you uninstall and reinstall the app the token will change**
2. Go to [Firebase Console](https://console.firebase.google.com) `A/B Testing` and click on `Create experiment` and in the pop up that opens select `Remote Config`
3. Set a title and select the correct app (**very important**) **`com.toggl.daneel.debug`**
At this point you can send the percentage of the users that will be part of the A/B Test.
![screen shot 2018-07-17 at 21 13 11](https://user-images.githubusercontent.com/885122/42838457-89edcda6-8a09-11e8-8f56-d348a4fec847.png)
4. Add the parameters 2 parameters that are available from the drop down menu **A**
Add some variants **B**
Add values for each variant **C** and **D**. If you do not set a value the default one will be used (same as the control group)
![screen shot 2018-07-17 at 21 14 08](https://user-images.githubusercontent.com/885122/42838675-169788a0-8a0a-11e8-93bd-6054f3723d42.png)
5. Select the goal you want to maximise with the test **A** (Events from the AppStore app will not be shown here unless the AppStore app ID is used in **step 3**
![screen shot 2018-07-17 at 21 14 31](https://user-images.githubusercontent.com/885122/42838837-80b93bca-8a0a-11e8-82e8-876a5f830b6a.png)
6. Now in order to add a device for testing so that it gets a specific variant for testing click the buttons as shown in the screenshots below
![screen shot 2018-07-17 at 21 23 37](https://user-images.githubusercontent.com/885122/42838910-b2fcaba8-8a0a-11e8-90ba-b4c16b17a529.png)
![screen shot 2018-07-17 at 21 23 46](https://user-images.githubusercontent.com/885122/42838918-b6b72fac-8a0a-11e8-8260-426adc7bf4fc.png)
Here in **A** we add the Token we got in **step 1** and in **B** we set the variant that we want this device to receive. Very important to click **C** otherwise nothing will be saved by going straight to **D**
![screen shot 2018-07-17 at 21 29 42](https://user-images.githubusercontent.com/885122/42838938-c8fe2b3e-8a0a-11e8-8b87-600374baf4ff.png)
7. Run the app and the values of the selected variant in **Step 6** should be shown in the pop up in the device as below
![screen shot 2018-07-17 at 21 30 12](https://user-images.githubusercontent.com/885122/42839133-5e31b8ce-8a0b-11e8-830e-29e237fffde0.png)
If you start and **stop** a timer the rating view should appear as we described in our variant.
![screen shot 2018-07-17 at 21 30 24](https://user-images.githubusercontent.com/885122/42839159-78b61cee-8a0b-11e8-95ab-c045d35036c1.png)

## For AppStore release
1. Perform **Steps 2 to 5** from the above section with the following changes: 
- In Step 3 select the **`com.toggl.daneel`** app
- After Step 5 select **`Start experiment`**

**Comment by juanlaube** [comment] 2018-07-24 16:37
The remote config and experiments part and when we ask users to rate us work fine for the three criteria. I have to play with this a bit more to test longer scenarios, but so far so good.

On the UI side, I've found some small problems:

- IMG0001: TE is behind the rate us view, empty state and welcome back are still visible. Pull to refresh solved the problem.
- IMG0002 & IMG0003: Onboarding tooltips are visible on top of the rate us view.


Finally, I've found a crash when launching the app after switching variants in the experiment for my test device, unfortunately (or not) this happened only once and I wasn’t able to reproduce the problem again, in fact, I successfully changed the variant several times.

IMG0001:
![img_0001](https://user-images.githubusercontent.com/8163330/43153059-a0c5a0c0-8f46-11e8-9234-24a519577413.PNG)

IMG0002:
![img_0002](https://user-images.githubusercontent.com/8163330/43153060-a0ebb27e-8f46-11e8-93d2-63b62675f7db.PNG)

IMG0003:
![img_0003](https://user-images.githubusercontent.com/8163330/43153061-a11620fe-8f46-11e8-9529-b6a185ff3a3c.PNG)

**Comment by juanlaube** [comment] 2018-07-24 18:08
I have found two bugs:

- The rate us view stays when leaving the app open for a while. Now, the issue description says _when user hasn’t interacted with the card in a 5 min, snooze it for 24h._

- The rating view won't be presented after 24 hs when the outcome is `NoInteraction` because there's an early return in MainViewModel, line275. That line should probably be `if (onboardingStorage.RatingViewOutcome() == RatingViewOutcome.NoInteraction) return;`

**Comment by juanlaube** [comment] 2018-07-24 18:42
Also I noticed there are no metrics info in the dashboard, but this could be some delay in Firebase. I will check that again tomorrow.

**Comment by sofokli1** [comment] 2018-07-25 13:43
about the tooltips. 
- aren't the tooltips shown only the first time the user logs in a freshly installed app?
- isn't the rating ui not shown on the first time the user opens the app?
- what are the chances the user will have to see the tooltips and the rating view at the same time?

**Comment by juanlaube** [comment] 2018-07-25 13:52
I created the issue https://github.com/toggl/mobileapp/issues/2732 for the snooze bug.

**Comment by juanlaube** [comment] 2018-07-25 13:57
The empty shouldn't happen in a normal situation, this was forced because I set the day count to 0.

@sofokli1 about the tooltips:
- those are shown for any user that didn't see them before, you can sign up, have 30 TEs and still see the tooltips.
- The rating UI is not shown when the user opens the app, it's based on the criterion from the remote config.
- I think it's possible for users to see both at the same time, you can sign up, create 4 TEs today, the next one in a week and at the same time you can see the rating view.

**Comment by sofokli1** [comment] 2018-07-26 12:16
PR #2721 fixes the onBoarding bubble showing on top of the rating view

**Comment by sofokli1** [comment] 2018-07-26 12:30
Regarding the empty states showing the rating view, it is virtually impossible since the triggers to show the rating view are `start a new time entry`, `stop an existing one` and `continue a time entry`. None of these are possible if the empty view is visible. Correct me if I am wrong.

@juanlaube and @amulware is anything else to address in this issue?

**Comment by amulware** [comment] 2018-07-26 12:32
Starting a new entry is possible with an empty log, and the new entry will not show in the log either.

But I don't think we have to cover this case, because it would mean the user hasn't done any tracking in the last two months, which is rare I think.

I'd like @juanlaube to confirm, but it seems we're good here?

**Comment by juanlaube** [comment] 2018-07-26 12:33
That's correct, we're good 🙂

**Closed** 2018-07-30 07:51 UTC
Labels: ios
