### ISSUE TITLE
iPhone 7 crashing

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#1234] opened 2018-01-05 02:29 UTC
case/618013

App crashes immediately to home screen after launch. Deletion and reinstall have not resolved the issue.

## Device details
**Network:** Verizon Wireless
**Capacity:** 32GB
**Available:** 12.63GB
**Version:** 11.2.1 (15C153)
**Carrier:** Verizon 31.1
**Model:** MNAC2LL/A (iPhone 7 Black 32GB)

**Comment by simonrozsival** [comment] 2018-01-05 10:01
Is this 1.0 or 1.1?

**Comment by ricotheque** [comment] 2018-01-11 02:33
1.1

**Comment by amulware** [comment] 2018-01-12 15:33
Do we have an iPhone 7 device at Toggl to test this?

If this only happens to a single user and cannot be reproduced (and maybe check if the problematic device is jailbroken), there is little we can do.

**Comment by amulware** [comment] 2018-01-12 15:35
If there are no steps to reproduce or some other information to go on when the containing milestone comes to an end, please close this.

**Comment by simonrozsival** [comment] 2018-01-12 15:39
I have an iPhone 7. I don’t experience this.

Is it possible that this user signed to the app and from that moment it crashes right after start? In that case it might be caused by some invalid data. 

I am quite sure it is not device related, because I have no problem with the app on my phone.

**Comment by ricotheque** [comment] 2018-01-18 09:39
@simonrozsival thanks, I've just asked the user if their device was jailbroken, and the exact moment when the app crashes.

**Comment by Michelle112** [comment] 2018-01-19 16:20
User replied that the phone is not jailbroken and crashes when they "try to look at the report for last year as a whole."

**Comment by amulware** [comment] 2018-01-19 16:24
That sounds very different than the original report. In either case, the reports-calendar crash is known, will be fixed next release.

I'm closing this. If there is something more concrete about the original case, feel free to reopen.

**Closed by amulware** 2018-01-19 16:24 UTC
