### ISSUE TITLE
Creating the first tag shows the placeholder text

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4110] opened 2019-01-07 13:12 UTC
## 🐛 Bug Report
After creating the first tag in the account from the start time entry view, the suggestions show a row with the placeholder text in interface builder ("Meeting with Alari").

## Context

Build/Branch: Daneel 1.14.2
Phone OS: iOS only
Phone model:

## Expected behavior
After the new tag is created and added to the description text field, suggestions shouldn't be visible.

## To reproduce
- Login with an account that doesn't have any tags or sign up
- Start a new time entry
- Create a new tag in the description
- 💥 You should see the row with the placeholder text now

![img_1126](https://user-images.githubusercontent.com/8163330/50769945-55fa3000-1264-11e9-9def-ecc5d949c06d.PNG)

**Comment by maritoggl** [comment] 2019-06-21 12:39
Could not reproduce, thus closing. If you confirm the issue is still present, please re-open.

**Closed by maritoggl** 2019-06-21 12:39 UTC
Labels: bug, ios
