### ISSUE TITLE
Reports section is weirdly resetting back to "this week"

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4331] opened 2019-02-04 09:35 UTC
## 🐛 Bug Report
The Reports view selected date goes back to "this week" every time, but the rest of the view does that only some times.

Also some flickering happens every time we show that view.

## Context
Build/Branch: 1.16.1 App Store version (also on current develop)
Phone OS: iOS 12.1.3
Phone model:  iPhone Xs

## Expected behavior
What should happen is this view remembers last set period (during the current session) and always shows that. Also no flickering.

## To reproduce
- Go to reports, select, for example, last year as the period
- Go to the main timeline
- Back to reports: The period will reset back to this week, and the rest of the view will sometimes also go back to this week, sometimes stay in last year.

## Suggestions
Wait until I merge the changes to table view sources to attempt to fix this.

**Comment by maritoggl** [comment] 2019-06-26 12:19
I have a feeling this has been fixed since first reported - I personally couldn't reproduce it. With that said, I understand this wasn't an issue that always happened, so I won't be closing it yet. Could anyone else try to reproduce the same?

**Comment by heytherewill** [comment] 2020-02-10 14:35
Obsolete since rewrite

**Closed by heytherewill** 2020-02-10 14:35 UTC
