### ISSUE TITLE
ArgumentOutOfRangeException in SegmentedRecyclerAdapter

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2733] opened 2018-07-25 14:48 UTC
## 💥 Crash Report
It seems something is going wrong with indices in the main recycler view while scrolling.

### 👥 Impact
- over 400 occurrences in the last two days
- which accounts for more than 2/3 of crashes in 1.1
- all sorts of phones

### 🔗 Context
Might be the same or related to this bug when syncing/scrolling at the same time: https://github.com/toggl/mobileapp/pull/2606

### 📡 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/b031945772c4dd339906538a5bb1e1a0be192dd1?appVersion=1.1

### 📝  Exception & Stack Trace
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
```cs
ThrowHelper.ThrowArgumentOutOfRange_IndexException ()
List`1[T].get_Item (System.Int32 index)
Collection`1[T].get_Item (System.Int32 index)
SegmentedRecyclerAdapter`2[TCollection,TItem].tryGetItem (System.Int32 viewPosition)
SegmentedRecyclerAdapter`2[TCollection,TItem].GetItem (System.Int32 viewPosition)
MainRecyclerAdapter.GetItem (System.Int32 viewPosition)
MainRecyclerView.findOldestTimeEntryView ()
MainRecyclerView.onFirstTimeEntryViewUpdate ()
ObservableExtensions+<>c__DisplayClass1_0`1[T].<VoidSubscribe>b__0 (T _)
AnonymousSafeObserver`1[T].OnNext (T value)
Merge`1+Observables+_+InnerObserver[TSource].OnNext (TSource value)
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
Subject`1[T].OnNext (T value)
FromEventPattern+Impl`2+<>c__DisplayClass3_0[TDelegate,TEventArgs].<GetHandler>b__0 (System.Object sender, TEventArgs eventArgs)
View+IOnScrollChangeListenerImplementor.OnScrollChange (Android.Views.View v, System.Int32 scrollX, System.Int32 scrollY, System.Int32 oldScrollX, System.Int32 oldScrollY)
View+IOnScrollChangeListenerInvoker.n_OnScrollChange_Landroid_view_View_IIII (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v, System.Int32 scrollX, System.Int32 scrollY, System.Int32 oldScrollX, System.Int32 oldScrollY)
```

**Comment by daividssilverio** [comment] 2018-07-26 00:33
Couldn't fix the problem today, but found some hints.

### What is going on
The problem is happening when scrolling while a full sync. It doesn't seem to happen on the initial sync.
Why? We are trying to access an invalid position on the `RecyclerView Adapter` at the very moment its ItemSource is updated. It boils down to that.

In the specific exception in this issue description, the chances of the invalid access happen are worsened because of this observable and its subscription method `onFirstTimeEntryViewUpdate`:
https://github.com/toggl/mobileapp/blob/94cb81229e4a9b8a5f4d4f2b077b821a4dc3eb74/Toggl.Giskard/Views/MainRecyclerView.cs#L68-L72

☝️ is happening a lot while scrolling, and it tries to access the last items on the adapter inside a loop based on the recycler view adapter item count, which can change during the loop.

### What have I tried
But, just changing/removing that piece of code doesn't fix the problem and it still happens when scrolling during the full sync. I also tried putting some guards on the places where GetItem from the adapter is being called, but it didn't fix the problem, only made internal java errors pop up (yes, java).

### Suggestions I thought could work
**Easy fix**: block the scrolling when doing the full sync with some Noise Layer with a ProgressBar (no scroll, no crash). This could be a temporary fix to prevent further crashes. It would be annoying to some users.
**RxFactor**: We could rxfactor the main log :) This would require a lot of work, the RecyclerView involved uses the `SegmentedRecyclerAdapter` which uses MvxObservableCollection and other inner classes. But this would most likely fix the problem for good and also give us better control over the adapter and its changes (we could use DiffUtil more easily then).
**Pinpoint the invalid accesses** and try not letting the RecyclerView/Adapter/LayoutManger make the calls that raise the exceptions (couldn't find them yet)

**Comment by amulware** [comment] 2018-07-26 08:56
I don't like the easy fix, and I don't like waiting for rxfactor 🙊

**Comment by amulware** [comment] 2018-07-26 08:57
That being said, will the refactor become a lot less work after @Odrakir is done with refactoring the ios main view?

**Comment by Odrakir** [comment] 2018-07-26 09:08
I couldn't say... It would probably imply some changes in Giskard as well... What I don't understand is the necessity of merging scroll events with collection changes in the code that Daivid posted... But I don't know, I might be missing something.

**Comment by kornelijepetak** [comment] 2018-07-26 09:25
The merging is related to onboarding, showing the tooltip on the correct list element when the list is being scrolled...
This onboarding destroyed our code... We should've done the onboarding the old school way 😛 with pictures and videos 😄 haha

**Comment by Odrakir** [comment] 2018-07-26 09:52
I see, is this code based on the iOS version? Because I'm refactoring that at the same time I'm doing the rxfactor. What I'm doing is just observing the scroll offset, and when it changes I take the first cell and position the onboarding hints over it.

What am I missing?

**Comment by daividssilverio** [comment] 2018-07-26 13:45
We decided internally tp amenize the problem while RxFactor is not done on iOS and Android for this problem.
What we will be doing is: To not access the recycler view items while sync Is running to prevent the main crash that is being reported. That won't fix the source problem, but it will potentially reduce the amount of crashes.

**Closed** 2018-07-27 13:49 UTC
Labels: android, crash
