### ISSUE TITLE
Deleted TE disappear after restarting the app

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#744] opened 2017-10-18 07:54 UTC
1) Deleting time entries either doesn’t work or crashes the app
2) When restarting the app after deleting a TE, TE disappears after the restart

**Comment by amulware** [comment] 2017-10-18 09:20
After internal discussion, this seems to be a duplicate of #688 and #689

**Closed by amulware** 2017-10-18 09:20 UTC
