### ISSUE TITLE
Holding backspace doesn't delete the first word

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5785] opened 2019-08-20 11:08 UTC
## 🐛 Bug Report
This is a follow up issue to #5474 and #5775. The behavior when holding the backspace button on the description field in the start time entry view has been fixed except for one case, it doesn't delete the first word.

## Context

Build/Branch: develop
Phone OS: iOS
Phone model:

## Expected behavior
Holding the backspace button should delete the first word too, it's not special or anything.

## To reproduce
Have a description long enough so the text field starts deleting by words when holding the backspace button.
Hold the backspace button and delete everything.

## Suggestions
I tried to fix this and couldn't find the problem. I found that changing the text in the text field triggers an update in the view model, which triggers an update in the view, couldn't link this to the problem as everything seems to work as expected, but don't discard that when looking into it again.

**Comment by Odrakir** [comment] 2019-09-10 11:33
@juanlaube 🤔 Are you sure this is fixed for whole words except for the first? It doesn't work for me at all when deleting starts trying to delete words. Latest develop.

**Comment by simonrozsival** [comment] 2019-10-07 12:33
I can confirm that the original fix does not work (at least on iOS 13).

**Comment by simonrozsival** [comment] 2019-10-07 13:24
I investigated this a bit and this is what I found:

The problem is in `StartTimeEntryViewController.onTextFieldInfo`, where we handle "sudden" changes of the text input. The following modification fixes the problem with backspace:

![image](https://user-images.githubusercontent.com/374616/66314927-19538600-e915-11e9-8a1f-ebf3d53ce250.png)

... but at the same time it messes up selecting our autocomplete suggestions. Oops.

Unfortunately the logic behind the text input is quite complicated and it is hard to reason about (also is has been rewritten many times to fix "small" bugs like this one with autocomplete, autocorrect, backspace, ...).

It would be best if we could have a list of criteria/tests which we could test to verify that we didn't break the business logic of this field/screen. Currently I can't see any in Notion or in the manual testing checklist for releases. This could be done as part of the fix of this bug (or at least marked as a follow-up issue).

**Closed** 2019-11-27 16:42 UTC
Labels: bug, ios
