### ISSUE TITLE
Syncing does not complete when flight mode enabled/disabled after TE started with Siri

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#3997] opened 2018-12-17 11:31 UTC
## 🐛 Bug Report
User reported that they have troubles with the app syncing after they start a time entry using a Siri shortcut and enable/disable flight mode once that's done. UI does not show that the syncing failed or succeeded - the sync just hangs in in process gray state. After restarting the app, issues do not continue. 

## Context
Build/Branch: 1.14.3
Phone OS: iOS 12.1
Phone model: iPhone 7

## Expected behavior
No matter what happens, sync either succeeds or fails, but does not remain in incomplete state. 

## To reproduce
1. Start a new time entry using a Siri shortcut
2. Enable flight mode
3. Disable flight mode
4. Open Toggl app

Recently created time entry appears as a running time entry, but syncing never seems to complete - the syncing indicator remains gray. 

Could not reproduce the issue when
1. The app was open before starting the time entry
2. Flight mode was enabled for several minutes

Also, after restarting the app, there were no further problems with the sync. 

Initially reported by user in [conversations/19865895810](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/19865895810), reproduced by myself.

**Comment by Odrakir** [comment] 2019-03-11 10:17
I can't reproduce it, and to be honest, it's a bit of a weird situation (enabling and disabling flight mode?)

Also if the entry does appear in the app it means it did sync, because the Siri extension communicates directly with the server, not the app.

So if there's an error here (which might have been fixed at some point, because no one can reproduce it). It's, apparently, not related to Siri.

I'm closing this issue.

**Closed by Odrakir** 2019-03-11 10:17 UTC
Labels: bug, ios
