### ISSUE TITLE
Implement Time Entry Grouping notification card

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4325] opened 2019-02-01 10:46 UTC
🏆 Implement the card that will notify the user about this new `TE Grouping` feature when it comes out.

The card will have:

* [ ] `View settings` button that has to lead the user to the settings screen
* [ ] `Got it` button that will discard the card

Since I need clarification on this thing, I have created only this one issue and it will be here until both platforms are done. When that happens, close the issue.
* [ ] iOS
* [ ] Android

### Clarifications needed

I would like @amulware @maritoggl @lizaPlotnikova to answer the following:
1. Besides tapping `Got it`, what are the other triggers for card discarding? Is it discarded by tapping `View settings` as well, or only if the user interacts with that particular option.
2. When exactly does this appear? Immediately after update to new version? Timed?
3. Note that we are not storing an independent value for the setting. We are utilizing whatever backend gives us (the same option can be set thru the webapp). By default the feature will be set to whatever value was set by the backend. Should the copy reflect that their current setting is this or that?

**Comment by maritoggl** [comment] 2019-02-01 11:08
1. Discarded by `View settings` as well.
2. I'd go with immediately after, but @lizaPlotnikova please confirm
3. Using the setting from backend is ok (and expected, really). @kornelije how much complexity would considering the setting for the copy that’s displayed add? I wouldn’t want this to be overengineered, but if we display only one copy, then good point, we should probably reword the text a bit and rather than saying “your time entries are now grouped together” say something along the lines of “time entries *can* now be grouped together” that would better suit both settings. But if it's super trivial, we should have the copy reflect the setting.

**Comment by amulware** [comment] 2019-02-01 11:46
Since I am pinged: Why do we need this at all?

**Comment by amulware** [comment] 2019-02-01 11:49
If we have this, what happens for people who install this version without having a prior one? What about people who logout? what about people who clear data, reinstall, etc?

Please make sure to cover all these cases.

**Comment by lizaPlotnikova** [comment] 2019-02-01 14:42
@kornelijepetak 
1) Discard by View settings as well ✅ (sorry that's in a comment in the "Flow" screen on Zeplin and I haven't had a chance to go back and add that bit in)
2)Immediately after update
3) The reason we're announcing this is that it's tied to the backend setting. I didn't spec out designs for both states of the setting – only for those that have it "on". But, I do think that announcing the feature to users who have the setting "off" would make sense. I don't think it's a huge deal though, because if the setting is "off" that means that the user intentional went into their profile on the web app and turned it "off" (because it's "on" by default). 

@Paul, my original idea (and spec in that Flow diagram) is to only show this to "existing" users who have gotten the update. (Meaning they're not new users, and they are not existing users who did not have a previous version installed.) 

The reason I think we need this is that users who haven't seen the "grouped" mode in the web app need to be notified why they're suddenly seeing "fewer" time entries. (We've basically gone into their kitchen at night and re-arranged where everything is. We should at least leave a note.) And we should point out how to "fix it". 

@maritoggl I'm not sure if you were around for this, but I remember that support got a lot of flack for when we introduced the "grouped mode" on web app and didn't tell people where to change the setting.

**Comment by maritoggl** [comment] 2019-03-05 14:09
@kornelijepetak from what I read, @lizaPlotnikova has covered the questions that were raised. Let's implement the card and show it only for the existing users that have the grouped mode turned on and got the update. 

Are there any other questions that haven't been covered yet?

**Comment by amulware** [comment] 2019-03-05 14:31
Given https://github.com/toggl/mobileapp/issues/4387 and the existing rating view, I want clear specs how this entire system is going to work, both UX wise and technically.

I don't want us to implement three different cards and run into all sorts of UI glitches or other unexpected behaviour because of it. We had enough trouble with rating view cards that I do not want to repeat.

This has not been thoroughly thought through. My questions above have not been addressed, and I'm sure there are other corner cases as well.

There is also nothing addressing how we detect that a user has updated, or how we make sure we don't notify them about the same thing more than once, or what and how we store any of the data required for this.

**Comment by maritoggl** [comment] 2019-03-06 11:59
Fair enough. We can set up a separate project for onboarding cards in the future, this is not a crucial item. 

Will close this for the time being. Meanwhile, @amulware, if you could share me more information about the troubles we had with introducing the rating view so I could consider the learning points in the future, that would be great.

**Closed by maritoggl** 2019-03-06 11:59 UTC
Labels: android, ios

**Comment by amulware** [comment] 2019-03-06 16:05
Generally, there were technical difficulties getting the cards done right without causing glitches in the main view due to the complexity of the screen. I trust we've learned from that, but anything around this area still needs a lot of testing.

My other points around having multiple cards, their potential interaction, etc. bother me much more.
