### ISSUE TITLE
Figure out what causes increase in 403 errors after Android app v1.14 was released

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5176] opened 2019-05-21 10:17 UTC
There was an increase in the number of users complaining about problems with syncing on thir Android phones after updating to Android app v1.14. The increase in errors is quite significant:

![image](https://user-images.githubusercontent.com/374616/58088014-0f2d2700-7bc2-11e9-883e-43cd2e435310.png)

These errors were mostly 403s (confirmed also by BE) and we have no idea, what causes them. There were no changes to the networking layer in 1.14. Most of the changes had something to do with DI refactoring.

**Comment by ApocalypticFish** [comment] 2019-05-21 12:32
Report from the user. 
Having some syncing issues once a day on Android I will get a sync issue, endless spinning and have to resign in to resolve.
So far haven&#39;t lost any data.
App name and version: Giskard/1.14
Device&#39;s time when sending this feedback: 20/05/2019 11:24:46 AM &#43;00:00
Last login: 28/04/2019 12:59:31 PM &#43;00:00
Manual mode is on: no
Number of time entries in our database in total: 95
Number of unsyncable time entries: 0
Number of unsynced time entries: 0
Number of workspaces available to the user: 1
Phone model: SM-G950F
Platform and OS version: Android 9
Time of last attempted sync: 20/05/2019 11:24:23 AM &#43;00:00
Time of last successful full sync: 20/05/2019 11:24:27 AM &#43;00:00

**Comment by ApocalypticFish** [comment] 2019-05-21 12:52
[Report from the user](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/22106488852)
the only time my app will sync after starting an activity is if I close it and restart it.
App name and version: Giskard/1.15
Device&#39;s time when sending this feedback: 5/20/2019 10:16:30 AM &#43;00:00
Device-based timezone: America/New_York
Last login: 5/1/2019 12:29:06 AM &#43;00:00
Manual mode is on: no
Number of time entries in our database in total: 1088
Number of unsyncable time entries: 0
Number of unsynced time entries: 0
Number of workspaces available to the user: 1
Phone model: Pixel 2 XL
Platform and OS version: Android 9
Time of last attempted sync: 5/20/2019 10:15:49 AM &#43;00:00
Time of last successful full sync: 5/20/2019 10:15:54 AM &#43;00:00
Toggl account based timezone: America/New_York

They also went on to explain that forcing sync doesn't help, only restarting the app.

**Comment by ApocalypticFish** [comment] 2019-05-21 13:01
[Report from user](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/22121231118)
sometimes the app fails to sync time entries... if you force kill the app it fixes itself. sorry no steps to reproduce, it&#39;s sporadic
App name and version: Giskard/1.14
Device&#39;s time when sending this feedback: 21/05/2019 8:54:36 AM &#43;00:00
Last login: 6/05/2019 1:34:44 AM &#43;00:00
Manual mode is on: no
Number of time entries in our database in total: 82
Number of unsyncable time entries: 0
Number of unsynced time entries: 0
Number of workspaces available to the user: 1
Phone model: Nokia 7 plus
Platform and OS version: Android 9
Time of last attempted sync: 21/05/2019 8:53:47 AM &#43;00:00
Time of last successful full sync: 21/05/2019 8:53:50 AM &#43;00:00

**Comment by heytherewill** [comment] 2019-05-22 15:34
After a bunch of investigation, this is happening because of a race condition during startup that leaves the sync manager in an invalid state. This is fixed in #5065

**Closed** 2019-06-07 14:59 UTC
Labels: android, api, mvexit
