### ISSUE TITLE
Incorrect calendar

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#3453] opened 2018-10-16 04:28 UTC
🐛 Bug Report
![image1](https://user-images.githubusercontent.com/17441860/46992830-c870dd80-d157-11e8-9750-1fa2a92a8909.png)

## Context
Calendar is showing the incorrect day for the date, Today is Tuesday the 16th of October 2018, but as you can see in this case the user is seeing Tuesday the 15th of October 2018.
Build/Branch: 1.12 (1993)
Phone OS: iOS 11.4.1
Phone model: TBD

conversations/19056444532

**Comment by maritoggl** [comment] 2018-10-16 10:50
Australia/Melbourne. The calendar remains on the previous day until 12:00pm (Midday). So it would seem that the calendar is switching to the next day at midday instead or midnight.

**Comment by simonrozsival** [comment] 2018-10-16 11:12
Melbourne is GMT+11. We are apparently not using the local time, but UTC time here.

**Comment by nicktoggl** [comment] 2018-10-17 00:13
Opening case is New York, Eastern time zone

**Comment by maritoggl** [comment] 2018-11-15 07:43
conversations/19557718403

**Comment by amulware** [comment] 2018-11-16 13:29
What is the status of this?

**Comment by juanlaube** [comment] 2018-11-19 11:53
I can't reproduce the problem as described in this issue. However, the problems described in those intercom conversations are solved now by #3723.

**Comment by juanlaube** [comment] 2018-11-19 11:55
I think we should close this issue unless someone can reproduce the problem with the date picker in the `EditDurationViewController`.

**Closed** 2018-11-30 12:32 UTC
Labels: bug, ios
