### ISSUE TITLE
Issue with deleting a TE while offline

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#6699] opened 2019-11-26 08:59 UTC
## ⛑️ User Support

While in offline mode, if they try to delete a time entry by swiping the TE just re-appears. 

## About the user

App version: Giskard/2.6
Phone OS: (waiting for info)
Phone model: (waiting for info)

## Expected behaviour
Swiping to delete a TE while offline should result in the TE no longer being visible (later on actually deleted when the phone goes online)

## To Reproduce
Go offline and swipe to delete a TE and wait a few seconds for it to re-appear

**Comment by heytherewill** [comment] 2019-11-26 11:15
Just tested this on current develop and I could not reproduce the bug. @VeljkoTN Can you reproduce it?

**Comment by VeljkoTN** [comment] 2019-11-27 09:08
@heytherewill I'm on 2.7 (internal tester) and they are on 2.6 so I had a problem reproducing as well and attributed to that. Anything they can try? (log out?)

**Comment by simonrozsival** [comment] 2019-11-27 09:16
Ref #6440

**Comment by VeljkoTN** [comment] 2019-11-27 11:40
This user is on Android 7.0, the device is Meizu pro7 if it helps, I didn't have that info when I created the issue.

**Comment by amulware** [comment] 2019-12-20 14:50
I'll close this, assuming that the above PR fixes this. Feel free to reopen/open a new issue if this persists.

**Closed by amulware** 2019-12-20 14:50 UTC
Labels: android, bug
