### ISSUE TITLE
Home screen shortcuts crash app

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#2698] opened 2018-07-19 07:16 UTC
## 🐛 Bug Report
Attempting to open the app via the home screen shortcuts causes a crash of the app. However using the shortcuts after successfully opening the app the "normal" way doesn't cause any crash.

## Context
I have been able to reproduce this with the public app (1.0), on my OnePlus 6 running Android 8.1.0

The crashing is probably related to #2695 

_Users device:_
Version: Giskard/1.0
Phone: Samsung Galaxy S7 (SM-G930F)
OS: 8.0.0 N_MR1

## Expected behavior
Tapping on any home screen shortcut should open the app with no issue.

## To reproduce
1. Install app
2. Log into app
3. Force-close app
4. Add app to home screen
5. Long-press on app's home screen icon to summon shortcuts menu
6. Tap on any item on the shortcuts menu (Start a time entry, Continue last entry, Reports)
7. See app crash
8. Open app by tapping on its icon on the home screen (keep trying until the app launches successfully)
9. Go back to home screen
10. Long-press on app's home screen icon to summon shortcuts menu
11. Tap on any item on the shortcuts menu (Start a time entry, Continue last entry, Reports)
12. See app work properly

## Suggestions
To be updated as we get new information.

Opening the app successfully the "normal" way will prevent the home screen shortcuts from crashing.

## References
/case/743565

**Comment by amulware** [comment] 2018-07-19 08:07
@ricotheque Your steps don't mention signing into the app after opening it. Is _just_ opening enough for the shortcuts to not crash? What do they do if not signed in? Or do they crash until the user signs in?

With regards to the solution to this, the shortcuts should only be shown if the user is logged in. And of course, then they should work. If the user logs out, they shouldn't be shown anymore, etc.

**Comment by ricotheque** [comment] 2018-07-20 01:54
Good point! I've updated the steps above.

No shortcuts show up when signed out of the app.

**Comment by willsb** [comment] 2018-07-25 14:44
I can confirm, after testing on current develop and on the Play Store version, that this particular issue is not related to the shortcuts themselves, but rather to the crash when opening, therefore it's basically a duplicate of #2695 and should be closed.

**Closed by willsb** 2018-07-25 14:44 UTC
Labels: android, crash
