### ISSUE TITLE
Buggy Japanese input when editing an entry

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#1311] opened 2018-01-24 08:57 UTC
case/634298

1. Tap play button to create new entry.
2. Type こんにちは into Description.
3. Tap on green check mark to confirm new entry.
4. Tap on running timer to edit running entry.
5. Tap on Description row to edit description.
6. Tap on keyboard backspace to clear current Description.
7. Tap on こ. Textbox shows こ
8. Tap on ん. Textbox shows ここん
9. Tap on に. Textbox shows こここんにん
10. Tap on ち. Textbox shows ここここんにちんにん
11. Tap on は. Textbox shows こここここんにちはんにちんにん

Video recording in case link; not shared here because user's time entries are visible.

**Comment by t-eimizu** [comment] 2018-01-25 02:14
Hi @ricotheque ,

Due to this bug, the evaluation on the App Store is falling in Japan.
I will wait for it to fix soon.

**Comment by simonrozsival** [comment] 2018-01-25 08:34
Is this 1.0 or 1.1?

**Comment by t-eimizu** [comment] 2018-01-25 12:32
@simonrozsival  
I confirmed that it will occur in version 1.1.
I am who reported this issue to the support.

**Comment by simonrozsival** [comment] 2018-02-02 10:02
@t-eimizu Thanks for the information and for reporting this bug! I will fix it today, so it will be included in the next week's release.

**Comment by t-eimizu** [comment] 2018-02-02 10:45
@simonrozsival Great! That's good news. :+1:

**Closed** 2018-02-02 17:23 UTC
Labels: bug, ios, pending-review
