### ISSUE TITLE
Reloading the main log (on midnight, significant time change) causes the app to crash

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3501] opened 2018-10-19 10:34 UTC
## 💥 Crash Report
From AppCenter sometimes the 

### 👥 Impact
The issues in AppCenter aren't grouped correctly. It is hard to say what the actual impact is.

### 🔗 Context
Happens on iOS 1.12.1

### 🛰 Link
There are several similar crashes which aren't grouped correctly:
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/53a33348720d0058d9053d6cc2f233d086acea59?appVersion=1.12
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/776193aea88c128dfc5880a1528be9aee8466fc1?appVersion=1.12

... and others. Just check AppCenter.

### 📝  Exception & Stack Trace
```cs
MainViewController.reload ()
```
Foundation.MonoTouchException: Objective-C exception thrown. Name: **NSInternalInconsistencyException Reason: attempt to delete and reload the same index path** (<NSIndexPath: 0x6f44f50> {length = 2, path = 0 - 2147483647}) Native stack trace: 0 CoreFoundation 0x1cc37b55 <redacted> + 152 1 libobjc.A.dylib 0x1bebf067 objc_exception_throw + 38 2 CoreFoundation 0x1cc37a19 <redacted> + 0 3 Foundation 0x1d52d52d <redacted> + 92 4 UIKit 0x2203deed <redacted> + 1770 5 UIKit 0x2203d67d <redacted> + 406 6 UIKit 0x2203d4e3 <redacted> + 40 7 Toggl.Daneel 0x00841fe8 Toggl.Daneel + 7704552 8 Toggl.Daneel 0x007da338 Toggl.Daneel + 7279416 9 Toggl.Daneel 0x0019c0b0 Toggl.Daneel + 733360 10 Toggl.Daneel 0x01245830 Toggl.Daneel + 18204720 11 Toggl.Daneel 0x0112f860 Toggl.Daneel + 17066080 12 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 13 Toggl.Daneel 0x01105c84 Toggl.Daneel + 16895108 14 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 15 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 16 Toggl.Daneel 0x01107ecc Toggl.Daneel + 16903884 17 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 18 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 19 Toggl.Daneel 0x01107ecc Toggl.Daneel + 16903884 20 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 21 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 22 Toggl.Daneel 0x011101d4 Toggl.Daneel + 16937428 23 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 24 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 25 Toggl.Daneel 0x01112f98 Toggl.Daneel + 16949144 26 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 27 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 28 Toggl.Daneel 0x0110bae4 Toggl.Daneel + 16919268 29 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 30 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 31 Toggl.Daneel 0x01107ecc Toggl.Daneel + 16903884 32 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 33 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 34 Toggl.Daneel 0x011071a4 Toggl.Daneel + 16900516 35 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 36 Toggl.Daneel 0x01248db0 Toggl.Daneel + 18218416 37 Toggl.Daneel 0x01226244 Toggl.Daneel + 18076228 38 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 39 Toggl.Daneel 0x010f2968 Toggl.Daneel + 16816488 40 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 41 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 42 Toggl.Daneel 0x01107ecc Toggl.Daneel + 16903884 43 Toggl.Daneel 0x00630498 Toggl.Daneel + 5534872 44 Toggl.Daneel 0x010b7704 Toggl.Daneel + 16574212 45 Toggl.Daneel 0x006306c0 Toggl.Daneel + 5535424 46 Toggl.Daneel 0x01117154 Toggl.Daneel + 16965972 47 Toggl.Daneel 0x010c0b24 Toggl.Daneel + 16612132 48 Toggl.Daneel 0x01117074 Toggl.Daneel + 16965748 49 Toggl.Daneel 0x010c1c7c Toggl.Daneel + 16616572 50 Toggl.Daneel 0x004d01f4 Toggl.Daneel + 4092404 51 Toggl.Daneel 0x004cbcf4 Toggl.Daneel + 4074740 52 Toggl.Daneel 0x004c9a58 Toggl.Daneel + 4065880 53 Toggl.Daneel 0x007aa7d4 Toggl.Daneel + 7083988 54 Toggl.Daneel 0x004cbb1c Toggl.Daneel + 4074268 55 Toggl.Daneel 0x005fccd4 Toggl.Daneel + 5323988 56 Mono 0x0255a759 mono_get_runtime_build_info + 962 57 Mono 0x025c69e3 mono_runtime_try_invoke + 116 58 Mono 0x025ef46d ves_icall_System_Threading_ThreadPool_IsThreadPoolHosted + 1062 59 Mono 0x025ed35f mono_threadpool_worker_set_suspended + 3400 60 Mono 0x025f5f4f mono_thread_internal_is_current + 436 61 Mono 0x025f5e15 mono_thread_internal_is_current + 122 62 libsystem_pthread.dylib 0x1c4bc93b <redacted> + 216 63 libsystem_pthread.dylib 0x1c4bc85d _pthread_start + 234 64 libsystem_pthread.dylib 0x1c4ba468 thread_start + 8 

```cs
Runtime.ThrowNSException (System.IntPtr ns_exception)
    Runtime.throw_ns_exception (System.IntPtr exc)
    (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
    (wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr,intptr,int)
    UITableView.ReloadSections (Foundation.NSIndexSet sections, UIKit.UITableViewRowAnimation withRowAnimation)
    MainViewController.reload ()
    ObservableExtensions+<>c__DisplayClass1_0`1[T].<VoidSubscribe>b__0 (T _) in <5b86cced65f646f4b5ee4833116b364d#424850f48412987ac4908aac3b759049>:0
    AnonymousSafeObserver`1[T].OnNext (T value) in <370f6a6bb34048878534065376a195cb#424850f48412987ac4908aac3b759049>:0
    (wrapper unknown) System.Object.gsharedvt_out()
    Merge`1+Observables+_+InnerObserver[TSource].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Where`1+Predicate+_[TSource].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Zip`3+Observable+_+SecondObserver[TFirst,TSecond,TResult].OnNext (TSecond value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Skip`1+Count+_[TSource].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    RefCount`1+_[TSource].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    Observer`1[T].OnNext (T value) in <370f6a6bb34048878534065376a195cb#424850f48412987ac4908aac3b759049>:0
    Subject`1[T].OnNext (T value) in <370f6a6bb34048878534065376a195cb#424850f48412987ac4908aac3b759049>:0
    (wrapper unknown) System.Object.gsharedvt_out()
    AsObservable`1+_[TSource].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    (wrapper unknown) System.Object.gsharedvt_out()
    Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
    (wrapper unknown) System.Object.gsharedvt_in()
    Timer+Periodic+_.Tick (System.Int64 count)
    (wrapper unknown) System.Object.gsharedvt_out()
    DefaultScheduler+<>c__DisplayClass7_0`1[TState].<SchedulePeriodic>b__2 ()
    AsyncLock.Wait (System.Action action)
    DefaultScheduler+<>c__DisplayClass7_0`1[TState].<SchedulePeriodic>b__0 ()
    ConcurrencyAbstractionLayerImpl+PeriodicTimer.Tick (System.Object state)
    Timer+Scheduler.TimerCB (System.Object o)
    IThreadPoolWorkItem.ExecuteWorkItem ()
    ThreadPoolWorkQueue.Dispatch ()
    Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback)
    _ThreadPoolWaitCallback.PerformWaitCallback ()
```

**Comment by simonrozsival** [comment] 2018-10-23 07:05
We should monitor if this issue disappears when #3513 is released to the users.

**Comment by amulware** [comment] 2018-11-16 13:29
What's the status here?

**Comment by sofokli1** [comment] 2018-11-19 11:49
@amulware I am trying to force reproduce this so that what need fixing becomes clear.

**Comment by amulware** [comment] 2018-11-19 12:34
Maybe also check app center if the crash still occurs in 1.13?

**Comment by sofokli1** [comment] 2018-11-19 15:58
since i do not see this crash in app center for 1.13.1 i am closing this.

**Closed by sofokli1** 2018-11-19 15:58 UTC
Labels: crash, ios
