### ISSUE TITLE
Project names not updating on Timer page

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1486] opened 2018-02-12 09:17 UTC
If a projects name is changed the app will refresh this on the most recent entry.

(Here I changed "Work" to "Work0")
![image](https://user-images.githubusercontent.com/18132080/36089787-dd4db1c4-0fdd-11e8-8b05-b37aada62d73.png)

(as you can see when you scroll further down that the other entries haven't updated even if I have forced sync)
![image](https://user-images.githubusercontent.com/18132080/36089806-f1bfa964-0fdd-11e8-92bb-22f118856d67.png)

(But when you click into the entry it displays the correct project)
![image](https://user-images.githubusercontent.com/18132080/36089818-fdb574b0-0fdd-11e8-82a6-40ea868afc7a.png)

**Comment by amulware** [comment] 2018-02-12 09:18
I take it you updated the project name online, and had the app sync for it to notice the change in the first place?

**Comment by ApocalypticFish** [comment] 2018-02-12 09:21
Yeah, updated the project on web.
Closed and reopened the app and it refreshes the data, however.

**Comment by amulware** [comment] 2018-02-12 09:23
Yeah, this is just a UI glitch where it doesn't bother updating the entries. I'm actually surprised it updates the last entry. What happens if you edit an older entry with that project (change description or whatever), then rename the project. I predict it would update the project name only on the last edited entry, not actually the newest one.

**Comment by ApocalypticFish** [comment] 2018-02-12 09:54
I can just open the project and confirm changes without actually changing anything and it updates on the timer page. it does this for each entry as it's opened and confirmed until they all reflect the change

**Comment by amulware** [comment] 2018-02-12 10:12
That's not what I meant. I mean that:
- you report the project name change only automatically happens for the last entry
- I think it happens for the entry that was EDITED last

This is due to the way we pull data. We will always re-pull the TE changed last (technical: since we use it's `since` date - it's a bit silly but the only way we can be sure we don't miss changes).

In either case, the bug is clear enough.

I'm not sure what the best way of fixing it is. Ideally, we could update time entries with a project, if said project changes. Alternatively, we could also just reload the whole log after completing a pull sync? If there are no graphical glitches, the latter might be the easiest and work just fine.

**Comment by simonrozsival** [comment] 2018-02-14 08:54
I think our best strategy to avoid this kind of bugs would be to redraw the whole log after we finish pull-sync (without the user noticing - e.g., preserving user's scroll position). It would be quite difficult to find individual entries which changed and should be re-rendered, at least I can't think of a reasonable way to do that right now.

**Comment by amulware** [comment] 2018-02-14 08:57
Well, we could compile a list of entries with associated data that changed, yada yada... if we can refill/replace/redraw the list without the user noticing, let's do that instead, agreed.

**Comment by maritoggl** [comment] 2019-06-21 11:46
I could not reproduce this problem either on Android or iOS. Perhaps this issue could be closed?

**Comment by maritoggl** [comment] 2019-06-21 12:02
Closing. Feel free to re-open if you need there's a need for that.

**Closed by maritoggl** 2019-06-21 12:02 UTC
Labels: foundation, glitch
