### ISSUE TITLE
Workspaces not changing correctly on settings page

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4815] opened 2019-03-27 13:56 UTC
## 🐛 Bug Report
Changed workspaces on the app both offline and online and it isn't recognising the change and still creating new entries in the default workspace.

## Context
Using an existing account with multiple workspace

Build/Branch:1.12
Phone OS:8.0
Phone model:HTC U Ultra

## Expected behaviour
The new entry should be created in the active workspace

## To reproduce
Swipe to a non-default workspace on the settings page and start and stop a new entry
Log into web or check the reports page and the new entries should be in the default workspace and not the active workspace.

## Suggestions

**Comment by amulware** [comment] 2019-03-27 14:16
Please use the correct labels.

**Comment by juanlaube** [comment] 2019-03-27 17:49
The default workspace sync correctly with the webapp, but that change is not reflected in the reports inside the app. I still have to check if this is a regression in this version.

**Comment by kornelijepetak** [comment] 2019-03-28 09:53
I am confused about this issue. It seems to work ok on 1.12.

First of all, from the perspective of our app, there is no difference between _active_ workspace and _default_ workspace. When a workspace is selected in the Settings view, it is propagated to our BE and can be shown as `Default` on this page here:

![image](https://user-images.githubusercontent.com/7033216/55147140-231a5680-5146-11e9-9de9-91fd752667ba.png)

These are the steps I've done (you can look at the picture):

1. Set Default workspace in options to `Personal`
2. Start a TE, set duration of 1:00:51, description: `personal`
3. Stop a TE
4. Go to settings view again
5. Set Default workspace to be `Work`
6. Start a new TE, set duration to 2:00:48, description: `work`
7. Stop TE
8. Open Reports on Webapp
9. Reports for both workspaces show correct data
10. Open Report screen in mobile app
12. Reports for both workspaces show correct data

Please advise if I've done something wrong and the problem still exists.

**Comment by arturs105** [comment] 2019-03-28 10:40
This seems like it is solved, since the time entries get created in the correct workspace and the reports show entries from the appropriate workspace as well.

**Comment by arturs105** [comment] 2019-03-28 10:42
Closing this, since 2 people verified, that the problem does not occur.

**Closed by arturs105** 2019-03-28 10:42 UTC
Labels: android, bug

**Comment by juanlaube** [comment] 2019-03-28 10:59
That's correct, I couldn't reproduce the issue either. One detail though, after switching workspaces, the default workspace in the reports tab is the selected workspace when the app launches, it's not a regression though, I confirmed this happens in iOS already.
