### ISSUE TITLE
1.16 Crashes/Freezes when continuing or deleting entries from 2 different workspaces

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4300] opened 2019-01-24 13:49 UTC
## 💥 Crash Report
The app freezes when you attempt to continue or delete multiple entries in quick succession from multiple workspaces.

### 👥 Impact
The app is frozen and you can't use it until you force close and reopen
### 🔗 Context
Signed into an account with multiple workspaces
Created an entry assigned to each workspace
Alternated continuing between each entry rapidly
App froze
Restarted
Attempted to delete the entries from two workspaces quickly
App froze.

**Comment by simonrozsival** [comment] 2019-01-26 11:08
Could you please create screen recording and attach it to this issue?

**Comment by amulware** [comment] 2019-03-05 10:45
- Please use the correct issue template, this one is for crashes from our automated tools, as should be obvious from the data to be filled in. There is another one for general bug reports.
- If this cannot be reproduced, close it.

**Comment by maritoggl** [comment] 2019-06-21 13:19
Closing as I couldn't reproduce this.

**Closed by maritoggl** 2019-06-21 13:19 UTC
Labels: crash, ios
