### ISSUE TITLE
Index out of range exception in reports table view source

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2105] opened 2018-05-10 15:08 UTC
One of the more common crashes in 1.5.

https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/6bebe5c5d134975ac7e16920ecc6ad6bd65ea3ba?appVersion=1.5
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource)
ThrowHelper.ThrowArgumentOutOfRangeException ()
List`1[T].get_Item (System.Int32 index)
(wrapper unknown) System.Object.gsharedvt_in()
IList.get_Item (System.Int32 index) in <0f7865fc4fbb4fddaab6f86c915ebae0#6388cdb77cc7e11608c230aa83e65725>:0
MvxEnumerableExtensions.ElementAt (System.Collections.IEnumerable items, System.Int32 position)
MvxTableViewSource.GetItemAt (Foundation.NSIndexPath indexPath)
ReportsTableViewSource.GetCell (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by simonrozsival** [comment] 2018-06-07 07:29
I think this issue was fixed by https://github.com/toggl/mobileapp/pull/2227 - this significantly changed the way we work with the list of the items for the table view source. There hasn't been any crash caused by this exception in `1.6` or `1.6.1`.

I suggest we close this issue and reopen it if this exception starts appearing again in AppCenter.

**Closed** 2018-06-08 09:34 UTC
Labels: crash, ios
