### ISSUE TITLE
Create workspace button allows for multiple interractions

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3855] opened 2018-11-28 17:18 UTC
## 🐛 Bug Report

Clicking the "Create workspace" button on the app in an account without a workspace doesn't lock the button or prevent further interaction so with slow sync/connection it's possible to create multiple duplicates workspaces
## Context

Build/Branch:
Phone OS:
Phone model:

## Expected behavior

The button should grey out and prevent further interaction once it has been pressed and only allow interaction again if the workspace creation has an error.
## To reproduce

Have an account with no workspace (this can be done by giving admin access to your workspace to another account and having that account remove the first from the workspace) 
It took a fair while for the workspace to be created and during that time I was able to click the button again and create a second workspace.

**Comment by amulware** [comment] 2018-11-28 17:21
Thought: This action should merely create the entity in the database and kick off a sync. It should take just a split second to do that.

**Comment by ApocalypticFish** [comment] 2018-11-28 17:22
Not sure if it's just a side effect of this, but the Default workspace selection prompt shows up after this and presents both new workspaces but it's not possible to select either.

**Comment by ApocalypticFish** [comment] 2018-11-28 17:22
Cannot dismiss the prompt now either

**Comment by amulware** [comment] 2018-11-28 17:23
Sounds like potentially a separate issue, should be investigated. :)

**Comment by ApocalypticFish** [comment] 2018-11-28 17:34
That prompt doesn't seem to show up another workspace seems to be selected automatically. So I'm not entirely sure why we have it.

**Comment by Odrakir** [comment] 2018-12-20 11:17
Mmmm... I'm trying to reproduce this and the app crashes when login in without a Workspace. So... I think I'll fix that first.

**Comment by Odrakir** [comment] 2018-12-20 11:49
I can't reproduce this. The button is disabled when tapped and never enabled again. I think this is probably an old bug that has been fixed with the introduction of RxAction.

**Comment by amulware** [comment] 2018-12-20 11:50
It still waits for the sync to complete though, doesn't it? That doesn't seem right to me. As long as the workspace was successfully created locally, we should let the user back into the app.

**Comment by Odrakir** [comment] 2018-12-20 11:51
That's right. I'll move the sync out of the action's observable.

**Closed** 2018-12-20 18:00 UTC
Labels: bug
