### ISSUE TITLE
Select workspace view can't be opened the second time

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#1146] opened 2017-12-11 15:37 UTC
1. Log in
2. Open settings
2. Open select workspace view
3. Swipe it down
4. Tapping on the workspace does nothing now

Pressing "x" to close the view works properly.

Tested on 1.0 from App Store and `develop` branch.

**Comment by simonrozsival** [comment] 2017-12-12 11:51
Does this happen also in the Simulator for you? I wasn't able to reproduce it.

**Comment by arturs105** [comment] 2017-12-12 11:53
Yes, happens on iPhone 8 iOS 11.2 simulator as well.

**Comment by simonrozsival** [comment] 2017-12-12 11:58
Could you give some more detailed instructions how to reproduce it or a GIF? Does it happen on some of our test accounts?

**Comment by arturs105** [comment] 2017-12-12 12:03
Tested on `test.account.2`

![dec-12-2017 14-01-10](https://user-images.githubusercontent.com/15633003/33883573-fae45ff4-df44-11e7-82d5-2154bf0b1798.gif)

**Comment by simonrozsival** [comment] 2017-12-12 12:05
Oh, thanks, I misunderstood the instructions, now it is clear to me.

**Comment by simonrozsival** [comment] 2017-12-12 12:23
So the problem is that swiping down, unlike pressing the close button, doesn't trigger the `CloseCommand` of the view model, so the `await` on line 124 of the `SettingsViewModel` doesn't return any value and it keeps waiting.

I probably won't be able to finish this today, so if someone starts working on it before I continue working on it (and assign this issue to myself), the solution will be to somehow pass the CloseCommand to the modal view so it calls it when it is closed by swiping down gesture.

**Comment by willsb** [comment] 2017-12-14 15:56
@pe0ny said she wanted to disable swiping altogether. This change @simonrozsival proposes is likely quite difficult to get done right, so it's better if we wait to see if swiping will be needed at all.

**Closed** 2017-12-19 22:36 UTC
Labels: bug, ios, pending-review
