### ISSUE TITLE
Cannot edit time entry after app runs in the background for a long time

### ISSUE THREAD

**Issue by nidarasheed** [toggl/mobileapp#5945] opened 2019-09-24 09:38 UTC
## 🐛 Bug Report

Cannot edit any time entry after leaving it runs in the background for a long time. 

## Context

Build/Branch: Giskard/2.3.1
Phone OS: Android 10
Phone model: Pixel 2

## Expected behavior

User should be able to edit time entry without issues. 
## To reproduce

1. Open Toggl app
2. Left it runs in the background for a long time
3. Open time entry view and resume the app
4. Tap on any time entry
Edit mode of any time entry won't open 

## Suggestions

[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23774830842)

**Comment by amulware** [comment] 2019-09-26 16:13
This looks pretty flaky, but let's see if we can reproduce this. If not, let's talk to support if this was an isolated case or something that's at all reproducible (maybe requesting more info from the user could help?).

**Comment by pdrj** [comment] 2019-09-30 14:38
Left some info in the [thread](https://toggl.slack.com/archives/C029WU7AY/p1569157762058700).

**Comment by ApocalypticFish** [comment] 2019-10-03 18:16
The user replied 

1. I am not really sure how long does it take or how many time I new to close then open the app to replicate the issue.

2. It still happens not once but multiple times a date.

3. The only thing that didn't work in the app is editing TEs

**Comment by ApocalypticFish** [comment] 2019-10-10 16:57
Another batch of replies:
1. I don't have time entry grouping enable.

2. I am pretty sure I save the new time entry every time I start a new one but I will keep an eye on that.

**Comment by pdrj** [comment] 2019-10-11 14:21
Tried to use the same locale as the user and also have some time entry descriptions in their language. No luck in reproducing so far.

**Comment by pdrj** [comment] 2019-10-28 11:42
Since the user had about 900 TEs, I'll try to repro this one with the help of @simonrozsival's script today.

**Comment by heytherewill** [comment] 2019-11-08 09:28
@pdrj Any progress on this one?

**Comment by pdrj** [comment] 2019-11-08 15:35
@heytherewill update posted in our slack channel.

**Comment by kornelijepetak** [comment] 2019-11-11 05:46
@pdrj Why? I mean, the Github issue should at least contain the summary of what was discussed and at least some kind of conclusion. But even when it's a top secret, please link to the slack conversation. Thanks 😄

**Comment by pdrj** [comment] 2019-11-12 08:18
`Why` is answered in the [thread](https://toggl.slack.com/archives/C02APMYTM/p1573227277187900).

Summary: no luck in reproducing.

**Comment by daividssilverio** [comment] 2019-11-12 14:12
@nidarasheed Do you have any other reports related to this issue? Is this still happening on android 2.5?

**Comment by nidarasheed** [comment] 2019-11-18 10:09
Nope, no more reports of this so  far :)

**Comment by heytherewill** [comment] 2019-11-19 19:06
I'm closing this for the time being since there were no reports of it since 2.5 and we're about to release 2.7. @nidarasheed feel free to reopen if a user reports it again 🙇

**Closed by heytherewill** 2019-11-19 19:06 UTC
Labels: android, bug
