### ISSUE TITLE
Non-overlapping TEs appear overlapping in Calendar

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6814] opened 2019-12-17 10:07 UTC
## 🐛 Bug Report
I had a time entry ending at 9:18. I then had a later time entry and resized it to start at the end time of the first entry (i.e. 9:18), which lead to the two of them displaying in different columns, instead of under each other in the calendar.

I then noticed that I have the same even with time entries where I stop one and then start another, so there's definitely no overlap there.

## Context

Build/Branch: 2.8-1
Phone OS: iPadOS
Phone model: iPad Pro

## Expected behavior
TEs should be in the same column, unless they actually overlap. In fact, I'd even say they should maybe be in the same column, unless they overlap for 60 seconds or more, to catch minor inaccuracies.

## To reproduce
Create time entries with matching start/stop times and find them rendering in different columns.

## Suggestions
Consider the 60s grace interval above (maybe check with product), for nicer rendering.

**Comment by sofokli1** [comment] 2020-01-08 17:05
@amulware are the durations of the overlapping TEs less than 15min? (any of them).

- If yes than it makes sense to show those overlapping since the UI representation of TEs of less than 15min is still 15min. This is a visual overlap only, not a logical one.

- There is also the case of editing the second TE manually and set its start time to the same as the end time of the previous. Although it is the same hour and minute, the seconds of the manually edit TE are 0sec which is different from the seconds of the previous TE end time which most likely is non 0sec. This will end up in a visual overlap as well as a logical one.

Let me know if you want changes to any of these behaviours.

**Comment by sofokli1** [comment] 2020-01-21 16:38
@amulware if the first TE has a duration of 2min 15 sec and starts at 1pm, it will look like a TE with a duration of 15. The next TE starts at 1:03pm with a duration of 15 min, it looks like 15 min in the cal. Although those are not intersecting and the difference is less than 60s there is no way to make those look in any way but in separate columns since there is no space to display the text of the first TE (which TE losses height?). The <60s rule will just make the code more complicated and from the example above it will need extra checks for those cases thus adding even more complexity. I would suggest to get designs first before making this kind of changes. @maritoggl any suggestion?

**Comment by maritoggl** [comment] 2020-01-22 10:55
Although I see a case for it given the way we currently record and display times, I'm with Eugene here and wouldn't add the 60s rule (complexity > benefit). I also understand why the current situation happens and would just live with it. With that said, perhaps there's a way to make the 15-minute rule a bit more flexible, somehow dependent on the zoom level? Was just checking that if the view is zoomed in, there's plenty of room to not make the time entries overlap. But I'm not sure if anything like that is easily feasible.

**Comment by juanlaube** [comment] 2020-01-22 15:42
I did some research and it's feasible but not an easy change. We need to decouple the min duration we assign to items from the layout calculator and the hours height from the layout, and calculate both based on the zoom scale in the same place. What would be the rule though? After a particular value of zoom we switch from 15m to 0?

**Comment by juanlaube** [comment] 2020-01-23 16:53
Unassigned myself until we know what we want to do.

**Comment by maritoggl** [comment] 2020-01-24 09:38
I would drop this. I understand it might be somewhat annoying to people that track short intervals, but other calendar apps (Google, iOS) have the same limitation when visualising events.

**Comment by piotr-chylarecki** [comment] 2020-02-13 03:55
> @amulware 
 (...) 
Although those are not intersecting and the difference is less than 60s **there is no way to make those look in any way but in separate columns** since there is no space to display the text of the first TE (which TE losses height?).
(....)

@amulware 
Just saying the issue is a regression.
I'm convinced I didn't experience it for months (auto-update turned on) when viewing short duration (<15 mins) TEs in calendar view prior to the bug's first appearance.

So, it's not like y'all need to figure out a new method to handle the issue - tracking down the relevant solutions for previous versions where it worked may suffice.

@maritoggl 
The way those app versions dealt with the problem of insufficient space for text display (low TE bar height on the timeline in Calendar view) is they cropped the outlying text. It's still available on selection (tap).
So, you already - de facto - did have a design solution in place, too.

**Comment by juanlaube** [comment] 2020-02-14 11:54
Closing this issue, the decision to keep it this way stands for now.

**Closed by juanlaube** 2020-02-14 11:54 UTC
Labels: glitch, ios
