### ISSUE TITLE
Strange Toggl logo on opening

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4195] opened 2019-01-14 16:31 UTC
When the Toggl app is opened with a hotspot active the Toggl logo appears to be winking at me.

**Comment by amulware** [comment] 2019-01-14 16:36
<img width="211" alt="screenshot 2019-01-14 at 16 29 05" src="https://user-images.githubusercontent.com/3987892/51126215-799c1800-181a-11e9-8757-aad2aedb83fc.png">

**Comment by arturs105** [comment] 2019-01-14 16:36
This affects all iPhones without a notch and can be easily tested on such a simulator by pressing ⌘Y or `Hardware` -> `Toggle in-call Status Bar`.

**Comment by arturs105** [comment] 2019-01-14 16:37
According to Juan: "a 1:1 aspect ratio constraint on the image in the splash should do it"

**Comment by juanlaube** [comment] 2019-01-14 16:43
Looks like Apple messed up in a recent update or something, I can reproduce this with other apps.

**Comment by amulware** [comment] 2019-01-14 16:44
If there is a non-hacky fix we can do that won't break again down the line, let's fix it anyways.

**Comment by juanlaube** [comment] 2019-01-14 16:47
Apps that have some custom launch screen animation doesn't have this problem (see twitter, uber, etc)

**Comment by Odrakir** [comment] 2019-01-15 11:38
After some research I came to the conclusion this is a bug in iOS 12 that causes a gap in the middle of the screen when showing the in call status bar. To avoid it we have 2 options:
- Hide the status bar when launching the app (just by setting a property in info.plist)
- Move the logo a bit up or down (probably up) so it saves that gap.

¿Any preference?

**Comment by amulware** [comment] 2019-01-15 11:41
Not sure I like either option.

If anything I'd go with the first, but it feels a bit disruptive as well, to hide the status bar just to show it again a moment later? Then again.. I guess some other apps (like twitter) do exactly this?

Should we just hide it then? Or close this and let Apple handle it?

**Comment by Odrakir** [comment] 2019-01-15 11:52
For whatever reason we are also currently hiding it during the on boarding, so if it's the first time you start the app it doesn't look *that* weird.

On the other hand, moving the logo up doesn't look that bad in my opinion (attaching examples).

There's a radar for this, but who knows when will Apple solve it.

The safest way is probably to hide the status bar, as that's the edge case and most users won't use the app with that bar anyway. I personally think moving the logo is fine too, so that's why I'm in doubt.

![launchscreen](https://user-images.githubusercontent.com/724743/51178915-5c238880-18c4-11e9-8995-c1082da76dae.jpg)

**Comment by amulware** [comment] 2019-01-15 13:34
Design/Product decided to move the logo. Proceed!

**Closed** 2019-01-15 16:24 UTC
Labels: glitch, ios
