### ISSUE TITLE
Various GroupedCollectionTableViewSource crashes

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1523] opened 2018-02-14 18:11 UTC
There are multiple but similar types of crashes all occuring in `GroupedCollectionTableViewSource`:

**Example**: `NSInternalInconsistencyException: Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (2) must be equal to the number of rows contained in that section before the update (2), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
`

  [📘 example of stack trace](https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/b8d9705249f6cc94759d26d52829e190758c1597)

This happens with variable values. Numbers vary accross different errors (probably depending on the amount of user data).

**Comment by simonrozsival** [comment] 2018-02-15 12:03
I think some of these might be caused by #1524 (but probably not all of them).

**Comment by amulware** [comment] 2018-02-19 08:47
This seems to account for the majority of our crashes.

[![](https://i.imgur.com/UE5bd27.gif)](https://www.youtube.com/watch?v=pFRFRwkDsog)

If no fix can be found, still post any information you gain through investigation for the benefit of others. :)

**Comment by willsb** [comment] 2018-02-22 12:20
This fix for this was shipped in [1.3.3](https://github.com/toggl/mobileapp/releases/tag/1.3.3). @kornelijepetak, since you are the one monitoring crash stats, please close this issue if the error no longer occurs in version 1.3.3 onwards.

**Comment by kornelijepetak** [comment] 2018-02-28 06:45
This issues was not solved by #1547, but it seems like #1588 will do the trick.
Today 1.3.3 came out to App Store. I will monitor today and tomorrow for this.
I will close the issue afterwards if everything is fine.

**Comment by amulware** [comment] 2018-03-05 15:37
As far as I know this has not been resolved yet.

**Comment by willsb** [comment] 2018-03-21 19:14
To be closed when #1727 is merged back into develop

**Comment by amulware** [comment] 2018-03-22 08:39
I'm fine closing issues when they are merged into a release branch as well. Also, this is superseded by #1784

**Closed by amulware** 2018-03-22 08:39 UTC
Labels: crash, pending-review
