### ISSUE TITLE
Verify if tag.at == null issue remains

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3599] opened 2018-10-31 09:18 UTC
Some time ago, we found out that Tag's `at` field can be `null` for some tags which caused some bugs until we implemented a workaround.

The relevant backend issue has since been closed: https://github.com/toggl/backend/issues/5182

Can we verify that this is no longer a problem? (Ideally, someone who had this issue with their own data could check, or maybe we even have a way of knowing if this happens to any of our users?)

If this is indeed fixed, we should remove our workaround (create a new issue after posting findings below). Otherwise, we'll create a new issue for backend.

Feel free to close this after either of those issues has been created.

**Comment by arturs105** [comment] 2018-10-31 11:18
The mentioned backend issue says that POSTing a tag returned a tag with `at == null`. I tried creating several tags and everything was fine, looks like the problem mentioned in the issue is solved. However, when GETting the list of tags, some tags still have `at == null`, for example, test account 2 has one such tag, so we can't remove the workaround yet.

**Comment by amulware** [comment] 2018-11-05 11:45
Ah, I didn't realise there were two issues here, not just one. Someone please create a new issue for backend for the GET thing, reference it here and also ping me in it. Then feel free to close this. :)

**Comment by arturs105** [comment] 2018-11-08 11:10
Issue created #7718, Paul pinged, closing this.

**Closed by arturs105** 2018-11-08 11:10 UTC
Labels: api
