### ISSUE TITLE
Trying to edit project in edit view crashes app

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#697] opened 2017-10-09 12:32 UTC

**Comment by simonrozsival** [comment] 2017-10-09 14:12
The problem is in `GroupedCollectionTableViewSource<T>` - the cast between `ItemsSource` and `GroupedItems` does not work as intended.

**Comment by simonrozsival** [comment] 2017-10-11 16:30
This is already fixed in `develop`, so I close this issue.

**Closed by simonrozsival** 2017-10-11 16:30 UTC
Labels: bug, pending-review
