### ISSUE TITLE
'Sequence contains no matching element' when fetching from Realm by id

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2103] opened 2018-05-10 14:59 UTC
This is currently the most common crashing exception in daneel-1.5 at about 30% of all crashes. I'm not exactly sure why it happens though. Not being able to see the actual generic type here is unfortunate. We're fetching a lot of entities by ID. It could even be a combination of multiple things and multiple entities I figure.

If we cannot figure this out, I propose we catch it in the generic class and log it with more information (like the type in question and maybe even the call site if possible) so that we can narrow it down.

https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/0c3e01c78bbf677f702dd442430f26f116717fca?appVersion=1.5
```
System.InvalidOperationException: Sequence contains no matching element

RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression node)
MethodCallExpression.Accept (System.Linq.Expressions.ExpressionVisitor visitor)
ExpressionVisitor.Visit (System.Linq.Expressions.Expression node)
RealmResultsProvider.Execute (System.Linq.Expressions.Expression expression)
RealmResultsProvider.Execute[T] (System.Linq.Expressions.Expression expression)
Queryable.Single[TSource] (System.Linq.IQueryable`1[T] source, System.Linq.Expressions.Expression`1[TDelegate] predicate)
RealmAdapter`2[TRealmEntity,TModel].Get (System.Int64 id)
Repository`1+<>c__DisplayClass3_0[TModel].<GetById>b__0 ()
BaseStorage`1+<>c__DisplayClass8_0`1[TModel,T].<CreateObservable>b__0 (System.IObserver`1[T] observer)
```

**Comment by amulware** [comment] 2018-05-10 15:04
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/6bb38a015555487cd487d1affa79e005491d82c2?appVersion=1.5

Another case of the exact same stacktrace. Not sure why it's listed separately on app center. Maybe a different call site?

**Comment by simonrozsival** [comment] 2018-06-05 11:05
List of places where we use `GetById`:
- `Foundation`:
    - `DeleteTimeEntryInteractor` (Time entries data source)
    - `GetWorkspaceByIdInteractor` (Workspaces data source)
    - `AreProjectsBillableByDefaultInteractor` (Workspaces data source)
    - `GetDefaultWorkspaceInteractor` (Workspaces data source)
    - `WorkspaceHasFeatureInteractor` (Workspaces data source)
    - `ProjectDefaultsToBillableInteractor` (Projects data source)
    - `IsBillableAvailableForProjectInteractor` (Projects data source)
    - `TimeEntriesDataSource.Update(dto)`
    - `ReportsProvider` (Projects data source) - caught
- `Foundation.MvvmCross`:
    - `SelectProjectViewModel.createProject` (Projects data source)
    - `StartTimeEntryViewModel.createProject` (Projects data source)
    - `EditTimeEntryViewModel.Initialize` (Time entries data source)
    - `EditTimeEntryViewModel.selectProject` (Projects data source + Tasks data source)
    - `EditProjectViewModel.pickClient` (Clients data source)

**Comment by simonrozsival** [comment] 2018-06-05 11:12
I think right now the only thing we can do in general is to wrap the `InvalidOperationException`s from Realm with our custom exceptions which will contain information about the type of the entity. If we had full trace we would be able to figure out what is the cause, but this is not enough...

**Comment by simonrozsival** [comment] 2018-06-07 07:31
I suggest we close this issue for now and wait until we collect some data from the next release, which will contain the #2390 exception which will give us a better idea on what is going on in the app.

**Closed** 2018-06-08 09:35 UTC
Labels: crash, foundation
