### ISSUE TITLE
Time entries not stopping correctly after coming back online

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4817] opened 2019-03-27 14:01 UTC
## 🐛 Bug Report
Start a time entry
Go offline (aeroplane mode)
Stop time entry
Go online
The entry will show as stopped on the mobile app and even as synced but on the web app it will still be running
Forced sync and restarted the app and it was to no avail

## Context
Using my existing account the entry also had unmet constraints (compulsory field missing)

Build/Branch: 1.12
Phone OS:8.0
Phone model:HTC U Ultra

## Expected behavior
The entry should be stopped on the server

## To reproduce
Explained above

## Suggestions

**Comment by amulware** [comment] 2019-03-27 14:16
Please use the correct labels.

**Comment by juanlaube** [comment] 2019-03-27 17:11
@ApocalypticFish I can't reproduce this issue. When I go back online, it doesn't sync until I force sync or some time passes (same behavior in 1.11.1), but after that the time entry is stopped in the server. Can you try again?

**Comment by ApocalypticFish** [comment] 2019-03-27 17:17
Okay, I'll have a look

**Comment by ApocalypticFish** [comment] 2019-03-27 17:44
Okay, this is really odd. It seems okay now. Whereas previously it was occurring every time

**Comment by juanlaube** [comment] 2019-03-28 11:00
I'm closing the issue because this cannot be reproduced.

**Closed by juanlaube** 2019-03-28 11:00 UTC
Labels: android, bug
