### ISSUE TITLE
Calendar: Multiday TEs are not shown properly

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6755] opened 2019-12-02 16:20 UTC
## 🐛 Bug Report
TEs that span across multiple days are displayed only on the starting day in calendar view
 
## Context

Build/Branch: android-2.8
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
Multiday TEs should be visible on multiple calendar pages

## To reproduce
Create TE in calendar
Edit TE's start time to yesterday
Save
= TE will be displayed only on yesterday's page

**Comment by amulware** [comment] 2019-12-20 14:37
Is this expected behaviour actually correct? @maritoggl?
Is this the same on iOS?

**Comment by amulware** [comment] 2019-12-20 14:38
Depending on the answer to my questions, consider adding the iOS label, and either  move this issue into the  📜 Backlog project or close it.

**Comment by maritoggl** [comment] 2020-01-06 11:54
Well, snap. On iOS it seems that multi-day time entries are not displayed at all. Creating a separate issue for that. 

As for the expected behavior vs not - it is expected in a sense that it doesn't surprise, since we did have that issue already when we only supported viewing only one day in the calendar. With that said, we should fix that.

**Closed** 2020-02-11 13:32 UTC
Labels: android, ios
