### ISSUE TITLE
Deleted and Continue bars get stuck on the screen.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4433] opened 2019-02-19 20:35 UTC
## 🐛 Bug Report
Continued 5+ entries and Deleted 5+ entries in quick succession. Haven't discovered the lower limit that this requires yet but the Continue and Delete bars gets stuck on the screen under some UI elements.
![image](https://user-images.githubusercontent.com/18132080/53045343-a84a8580-348d-11e9-9b25-f9082b7b67ae.png)

I made you a video but it's MP4 so here's a link.
https://toggl.slack.com/archives/C02APMYTM/p1550608375956600

## Context
Continued and deleted several entries on an old workspace in succession (all entries are in the one workspace)

Build/Branch: 1.11
Phone OS: 8.0.0
Phone model: HTC U Ultra

## Expected behavior
These should disappear completely once done

## To reproduce
Continue and delete lots of things quickly.

## Suggestions
https://youtu.be/xhy7dXWjpAA

**Comment by amulware** [comment] 2019-02-26 12:16
If this can still be reproduced after 🔟: https://www.youtube.com/watch?v=pFRFRwkDsog

**Comment by juanlaube** [comment] 2019-03-25 16:56
I've been fighting with this for hours and couldn't find a solution yet. I will unassign myself from this and take a look again once GTE is merged.

**Comment by ApocalypticFish** [comment] 2019-03-27 16:38
Sorry man, still happening.
![image](https://user-images.githubusercontent.com/18132080/55094669-1dc1fb00-50b7-11e9-9d9a-81cf4ec67912.png)

**Comment by daividssilverio** [comment] 2019-03-28 13:13
Un-assigning myself for now, I'll take a look again if no one else does.

**Comment by kornelijepetak** [comment] 2019-05-13 08:22
I was unable to find a proper solution to this issue.

Well, there are two different issues here.
1. When quickly swiping, some red/green labels remain visible (such as described in multiple screenshots in this issue)
1. When quickly swiping, some of the items are shown in the list's layout, but look empty, as if the cell is set to invisible. It's not invisible, just probably not redrawn after animations, or still outside of bounds (after swiping). Just touching the _glitching_ item again will reset it and it will be normally visible.

* 1st one I can't reproduce after #4985. That PR actually made the problem described in this issue even harder to achieve.
* 2nd one I can reproduce when trying really hard.

In general, I think that after swiping in general was made more difficult, this whole issue is no longer really problematic. The solution to the problem could also be really messy and hackish, but I'm not really 100% sure why it happens (need more @toggl/androids help), so it's hard to say.

But I'd like @ApocalypticFish to try again if he can break it after #4985 (current `develop` basically).

> ℹ **More info**. The problem I believe is in the asynchronicity of diffing, updates and animations. Multiple swiped items (and their corresponding backgrounds) can be visible at the same time because we are not updating the view immediately, but as a reaction to diffing and update. And diffing can take some time so that I can freely swipe another item while the first one is still processing...

**Comment by kornelijepetak** [comment] 2019-05-13 08:30
For the time being, I am closing this issue. While it can theoretically still occur in the app, I believe that with the normal app use, it will not happen.

If users start to complain, we'll reopen the issue and continue our search for the solution.

**Closed by kornelijepetak** 2019-05-13 08:30 UTC
Labels: android, bug
