### ISSUE TITLE
Full month not displayed in Android calendar view

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#3641] opened 2018-11-05 08:50 UTC
## 🐛 Bug Report
User is trying to edit the start/stop date of the time entry, but the calendar does not display the date they want to set. Month seems to end before it really does :)

## Context
Screenshots are available in conversations/19330193771

Build/Branch: Giskard/1.5.2
Phone OS: Android 5.1.1 
Phone model: Galaxy J7

## Expected behavior
All dates in a month are displayed in calendar view.

**Comment by daividssilverio** [comment] 2019-08-13 21:29
Hey @maritoggl , isn't this issue deprecated already? The wheel view being was introduced in droid 1.11. We are using stock views with very little customization now to edit start/end dates.

**Comment by pdrj** [comment] 2019-08-15 10:20
I think this might be an Android 5 'issue'. The screenshots below were taken on an API 22 device with the **current** app version.

<img width="473" alt="Screenshot 2019-08-15 at 11 45 28" src="https://user-images.githubusercontent.com/53510080/63088718-072d1b00-bf56-11e9-9f7d-9168b0466a65.png">
<img width="466" alt="Screenshot 2019-08-15 at 11 45 36" src="https://user-images.githubusercontent.com/53510080/63088731-114f1980-bf56-11e9-95fa-9e4300a9642b.png">

As you can see, the selected date can sometimes be invisible, but that is due to how the calendar is displayed in Android 5 and the scroll position.

I wanted to test it with v1.5.2 - the version reported in [the conversation](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/19330193771) - but:
- APKs I got won't install on an emulator - INSTALL_FAILED_NO_MATCHING_ABIS and I currently have no access to an Android 5 device
-  I managed to build v1.5.2 in VS and install it on an emulator, but it won't let me login/signup. Do we disable access for old versions?

In any case, I think this issue is pretty safe to close. To be completely safe, someone could grab v1.5.2, manage to login on a device and confirm my suspicions.

**Comment by heytherewill** [comment] 2019-08-15 11:34
I don't think we need to install older versions of the app for testings; if it can't be reproduced on the current version, then the issue can be closed. I will test this on lollipop and let you know

**Comment by heytherewill** [comment] 2019-08-15 12:23
Just checked on my peasant-tier phone running Lollipop as a terminal version and the bug is not there. Closing as fixed.

**Closed by heytherewill** 2019-08-15 12:23 UTC
Labels: android, bug, up-for-grabs
