### ISSUE TITLE
Login screen: Forgot password link covered up by keyboard in error state

### ISSUE THREAD

**Issue by lizaPlotnikova** [toggl/mobileapp#2450] opened 2018-06-12 19:39 UTC
When a user's seeing the "Icorrect email/password" message, it's more likely that they've forgotten their password. So, it might be helpful if they could see immediately where to go to recover from the error.

There are 2 deviations from the original designs in the current implementation:
 1) Too much space between error message and text field
![too much space](https://user-images.githubusercontent.com/24964497/41312260-9ed4021a-6e54-11e8-9c95-c952ac8b2a84.png)
Space should be 6dp or close to that. 

2) *more importantly,* Fields should lose focus and the keyboard should close. (We don't know if it's the password or the email that is incorrect anyhow). 

Please check out designs: 

<img width="422" alt="screen shot 2018-06-12 at 3 30 18 pm" src="https://user-images.githubusercontent.com/24964497/41312645-9720e9ec-6e55-11e8-9751-41d6e09c91df.png">

https://zpl.io/bo0nZ5E

**Comment by daividssilverio** [comment] 2018-06-12 22:39
I'm sorry, I added the android label because of the images. Should this be done in iOS too (the keyboard part)? iOS is showing the same behaviour if you click on the `Log In` button without closing the keyboard first.

I don't like the idea of closing the keyboard when the user clicks on the `Log In` button, because it might  be unexpected behaviour for the user IMO.

Something else that could be done is detected that the user has finished typing his e-mail/password and when he presses the checkmark on the keyboard, which closes it, we also execute the login action.

I'm talking about this checkmark, the "actionDone" imeAction, on android.

<img width="322" alt="screen shot 2018-06-12 at 6 36 44 pm" src="https://user-images.githubusercontent.com/2173493/41320935-bf6dbae6-6e6f-11e8-8439-9444bd9d5e3d.png">

**Comment by lizaPlotnikova** [comment] 2018-06-13 12:48
@daividssilverio I checked Facebook and Instagram apps on Android to see what they do when an incorrect username+password combo is entered. Both apps collapse the keyboard (and somewhat bizarrely, display the error message in a dialog). So, I don't agree with your case that it is unexpected behavior. 

That said, I don't think the keyboard needs to collapse on the button press... but instead could collapse when the error is returned. 

@pe0ny what do you think, should this behave the same on iOS? (I would recommend if it's likely that "Forgot password" is covered up by the keyboard).

**Comment by lizaPlotnikova** [comment] 2018-06-13 12:52
>Something else that could be done is detected that the user has finished typing his e-mail/password and when he presses the checkmark on the keyboard, which closes it, we also execute the login action.

Oh! I didn't catch that this action wasn't happening already. I agree that the "actionDone" key should also execute the login action. I agree that it should.

**Closed** 2018-12-19 13:58 UTC
Labels: android
