### ISSUE TITLE
Workspace preferences are not propagated when you go online after switching workspaces offline

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6585] opened 2019-11-14 22:46 UTC
To replicate:
1. Have at least two workspaces A, B
2. While online, be on workspace A
3. Check that the webapp also has the workspace set to A
4. Go offline
5. In the mobile app, switch to workspace B
6. Go online & Sync
7. Go to the web app and refresh
9. Sync again
8. Check that the web app is still on workspace A and now the mobile app is also on workspace A.

**Comment by semanticer** [comment] 2020-01-09 10:48
> Check that the web app is still on workspace A and now the mobile app is also on workspace A.

Or even better: 

<img width="601" alt="Screenshot 2020-01-09 at 11 48 21" src="https://user-images.githubusercontent.com/535613/72061328-f0f17400-32d5-11ea-97a1-aeb3fffe6cf4.png">

**Comment by semanticer** [comment] 2020-01-09 14:16
To get the Ooooooops error above 👆you just need to switch workspace in airplane mode.

**Comment by semanticer** [comment] 2020-01-09 15:19
@daividssilverio what should be the correct behavior? It looks like on iOS the workspace setting on web and in the app is completely separate and doesn't influence each other - is that the correct behavior?

**Comment by semanticer** [comment] 2020-01-09 15:45
I created separate issue for the generic ooops page https://github.com/toggl/mobileapp/issues/6888

**Comment by daividssilverio** [comment] 2020-01-09 15:47
From my point of view, if it works when it's online, I see no reason for it not to work when going from offline and then back online. And if it works on android, I see no reason for it not to work on iOS.

Btw @semanticer , I'm talking about the default workspace settings in this issue. The report's workspace changes separately and does not sync anything.

Correct me if I'm wrong here @amulware and @maritoggl .

**Comment by maritoggl** [comment] 2020-01-10 10:34
Correct. Report workspace selection is different from default workspace selection. Changing workspace in the report view should not affect the default. 
I would perhaps even simplify that issue by leaving webapp out from the description. Mainly because if we mix webapp in as well, one could maybe argue that webapp has synced the workspace data after mobile has. The same problem can be replicated with mobile only - go offline, change default workspace from A to B, go back online, sync, see that default did not get synced from mobile and is back to A. This, indeed, seems erroneous. Replicated that on iOS.

**Comment by semanticer** [comment] 2020-01-10 16:32
@daividssilverio Yeah I completely misunderstood the issue. On the plus side, I now understand our "test cases" much better 😁

**Comment by semanticer** [comment] 2020-01-10 16:49
I just wonder how do they do it on iOS, since the logic should be the same.
What is happening on Android now:
When you change the workspace in airplane mode we are not able to send https://mobile.toggl.space/api/v9/me PUT with workspace update as usual.
When you then proceed to sync with an internet connection you emediately receive the latest web's version of default workspace via https://mobile.toggl.space/api/v9/me GET

**Comment by semanticer** [comment] 2020-01-13 13:44
As discussed here https://toggl.slack.com/archives/CD40QCV25/p1578674961016700 after some explanation from @simonrozsival and more testing done by me it is now clear the issue is on our API and all local changes are not kept when they are "older" than 1 min. 

Simon on slack: 
> I will happily explain what the problem is :slightly_smiling_face: the server updates the at of the user’s record every minute. Our syncing algorithm will think that server has more up-to-date information and conflict resolution will throw away local changes.

I'm therefore closing the issue now.

**Comment by semanticer** [comment] 2020-01-13 14:00
More context from Sync Magicians https://toggl.slack.com/archives/CDRNW2N1F/p1578923422026100

**Comment by simonrozsival** [comment] 2020-01-17 15:44
We must switch from `at` to `updated_at` field using a JSON serialization attribute in the `Toggl.Networking.Models.User` class. Then syncing of user's data (default workspace) will start working. For more infromation check: https://toggl.slack.com/archives/C02APMYTM/p1579274738042600

**Comment by heytherewill** [comment] 2020-01-30 20:10
iOS is also affected by this

**Closed** 2020-02-11 13:07 UTC
Labels: android, bug, ios
