### ISSUE TITLE
Investigate running time entry widget not responding to push notifications

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6989] opened 2020-01-24 18:06 UTC
Title says it all.

How to replicate:
1. Be logged in;
2. Make sure that PNs are working when you have the app open in the main log. You can start/stop time entries from the web app to test that;
3. Do the same for the running time entry widget.

On my case, PNs did work in the main log, but not for the widgets.

Tested on Android 10, Samsung Galaxy Note 10.

**Comment by heytherewill** [comment] 2020-01-28 16:44
I could not reproduce that on current develop, but I think it might be worth doing some more testing on the Play Store version once 2.10 is out for users. With that in mind, I'm moving this issue to 2.12

**Comment by heytherewill** [comment] 2020-02-10 13:38
Confirmed that this works on 2.10 normally. Let's keep an eye on this, but it should be fine

**Closed by heytherewill** 2020-02-10 13:38 UTC
Labels: android, bug
