### ISSUE TITLE
Show onboarding phase 2 step 2 only once

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2597] opened 2018-07-04 07:18 UTC
Related to #1647 and #1520

The "Categorize your time entry with projects" tooltip currently shows every time the user enters the Edit view clicking on a Time entry that doesn't have a project yet.

It should stop showing that tooltip when the user closes the Edit TE view or navigates to any other screen.

**Comment by amulware** [comment] 2018-12-19 14:14
@daividssilverio Does this still happen? I haven't seen this.

**Comment by daividssilverio** [comment] 2019-01-18 12:52
I'll check later today.

**Comment by maritoggl** [comment] 2019-06-21 11:51
Couldn't reproduce. Could we perhaps close this?

**Comment by maritoggl** [comment] 2019-06-21 12:02
Closing. Feel free to re-open if you need there's a need for that.

**Closed by maritoggl** 2019-06-21 12:02 UTC
Labels: android, foundation, ios
