### ISSUE TITLE
Sync doesn't work when the app is in background or closed

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5450] opened 2019-06-18 19:58 UTC
After testing the droid app, I've found that:
- when the app is in foreground: runs like a charm!
- when the app is in background:
-- if the app was in foreground in the last few seconds/minutes: works alright
-- if the app was closed: nope... doesn't work
-- if the app has been in background for like 10 mins or so: nope... doesn't work

I suggest we either create a `JobService` to light sync the app in background with more time and actually finish it properly.

We can actually throttle incoming push notifications while the app is in background and avoid consuming more battery power than we should.

Another idea is to mark the app somehow to trigger a sync the next the app is opened.

**Comment by simonrozsival** [comment] 2019-06-19 14:19
- throttling locally could be a good idea, we might get a burst of notifications. If android allows you do do it easily somehow, do it
- do you think that the problem is that the app has just a short amount of time to run? can you somehow verify that the sync was actually triggered, but it didn't finish?

**Comment by daividssilverio** [comment] 2019-06-19 14:53
> throttling locally could be a good idea, we might get a burst of notifications. If android allows you do do it easily somehow, do it

I'll see what can be done. It should work alright.

> do you think that the problem is that the app has just a short amount of time to run? can you somehow verify that the sync was actually triggered, but it didn't finish?

Yes! I've put logs everywhere, it starts the sync process, but never finishes, the process being killed before it has a chance to finish.

**Comment by simonrozsival** [comment] 2019-06-19 15:19
How far does syncing get before OS kills it? Is it because of remote config?

**Comment by daividssilverio** [comment] 2019-06-19 15:33
1. It runs the `TogglApplication`'s setup.
2. Receives the message on `TogglFirebaseMessagingService:OnMessageReceived`
3. In the `RunSyncInteractor`'s `Execute`:

```
 public IObservable<SyncOutcome> Execute()
        {
            var meassuredOperation = sourceState == PushNotificationSyncSourceState.Foreground
                ? MeasuredOperation.FullSync
                : MeasuredOperation.PullTimeEntriesSync;

            var syncTimeStopwatch = stopwatchProvider.Create(meassuredOperation);
            syncTimeStopwatch.Start();

            analyticsService.PushNotificationSyncStarted.Track(sourceState.ToString());

            var syncAction = sourceState == PushNotificationSyncSourceState.Foreground
                ? syncManager.PullTimeEntries()
                    .LastAsync()
                    .ThenExecute(syncManager.ForceFullSync)
                : syncManager.PullTimeEntries();

            >>>>>>>> FIRES THIS CALL <<<<<<<<
            return syncAction.LastAsync()
                .Select(_ => SyncOutcome.NewData)
                .Catch((Exception error) => syncFailed(error))
                .Do(outcome =>
                {
                 >>>>>>>>> NEVER EMITS <<<<<<<<<<<
                    syncTimeStopwatch.Stop();
                    analyticsService.PushNotificationSyncFinished.Track(sourceState.ToString());
                });
        }
```

**Comment by daividssilverio** [comment] 2019-06-19 15:38
It's not because of remote config, I've disabled it for the tests.
`PushNotificationsConfiguration`'s values are always true on my tests. There's not even a request for the remote configurations in my tests.

**Comment by simonrozsival** [comment] 2019-06-19 15:41
Then I guess we need more time because we can’t make it any shorter.

**Comment by simonrozsival** [comment] 2019-06-24 15:40
Implementation was merged into the project branch.

**Closed by simonrozsival** 2019-06-24 15:40 UTC
