### ISSUE TITLE
Disable initial scrolling in the edit view

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#637] opened 2017-09-26 12:45 UTC
Currently edit view can be scrolled upon opening, however scrolling should become active only when the edit view has grown to the maximum size (due to too many tags or something else) and still needs more space.

**Comment by kornelijepetak** [comment] 2017-10-16 13:21
Did you mean that 

1. ... edit view should grow if needed until it fills the whole screen and then start allowing scroll

or 

2. ... the edit view's height should remain fixed, but the inner scrollview should allow scroll only when the size of the containing edit view is reached?

**Comment by amulware** [comment] 2017-10-16 13:24
I believe 2, but this is @pe0ny's call.

**Comment by pe0ny** [comment] 2017-10-16 13:28
Well. I would say 1.

> 1. edit view should grow if needed until it fills the whole screen and then start allowing scroll

That as well. When description/project/task/client name is really long, it should grow until fills the whole screen and then it should allow scrolling.


Edit view's height should be fixed only when content for inputs fit into one line (so called ideal case).

At the moment the problem is that edit view is fixed and it shows scrollbar when there's no need for that.

**Comment by arturs105** [comment] 2017-10-16 13:32
When i was creating the edit view, I was able to disable the scrolling if i set the size of the edit view to be a bit bigger (through `PreferredContentSize` property). But probably another solution is needed.

**Closed** 2017-10-30 10:42 UTC
Labels: pending-review
