### ISSUE TITLE
Editing text in the Description field not working as it should

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1899] opened 2018-04-17 09:14 UTC
Copied from: https://github.com/toggl/mobile/issues/1995

Let's say this is my time entry description: `Travelling from home to the library`. Now let's say I continue that time entry but want to swap the word "home" with "work". Normally, I'd just double-tap the word "home" and input a different one. But, when I start typing I'm also deleting the text after the highlighted word. 

Basically, the text field is in overtype mode, not the insert mode. If you ever used Windows, it's the mode you activate by hitting the "insert" key. 

Here's the two screenshots. 

1. screenshot. I select the word "From" 
![img_0165](https://user-images.githubusercontent.com/19473351/38774804-b8ca7670-4070-11e8-816c-fdaa60d5dc7b.png)

2. screenshot. Typing in the word "new"
![img_0167](https://user-images.githubusercontent.com/19473351/38774805-bfe2ad6a-4070-11e8-8c8f-4f7ef35a25e8.png)

---
Case: 605341

**Comment by arturs105** [comment] 2018-04-24 14:49
Could not reproduce, so closing

**Closed by arturs105** 2018-04-24 14:49 UTC
Labels: glitch, ios

**Comment by simonrozsival** [comment] 2018-04-24 14:50
This issue was probably fixed by https://github.com/toggl/mobileapp/pull/1892
