### ISSUE TITLE
App not responsive when coming from background

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5757] opened 2019-08-13 14:51 UTC
## 🐛 Bug Report
I'm just using the app normally, get back after a few, or a few more minutes to stop my timer, and I can't. Nothing in the app reacts. However, the timer-animation (long description going left/right) is still working. The timer itself isn't though, it appears stopped (usually at a much smaller time than it should actually be).

I have to force quit it, and it actually take it a good 10 seconds or so to obey before restarting the app.

## Context

Build/Branch: AppStore 2.2
Phone OS: iOS 12.3.?
Phone model: iPhone 6S

Looks to be the same as https://github.com/toggl/mobileapp/issues/5221 but it happens to me almost every day now, which fells more common than in the past.. but maybe that's just bad luck.

## Expected behavior
It should never freeze. The app should resume normally.

## To reproduce
- start a time entry
- let app go into background
- come back after 10+ minutes
- sometimes it's frozen, sometimes it isn't

**Comment by dshr** [comment] 2019-09-18 10:25
Tried reproducing this both on device and in simulator repeatedly to no avail. My hunch is that it's a BG sync that ends up taking too long, but haven't got any proof yet.

**Comment by amulware** [comment] 2019-09-18 14:20
I'm still getting this at least once or twice a week, on both my iPhone and iPad. Unfortunately, that's all I know.

**Comment by juanlaube** [comment] 2019-09-25 14:14
I couldn't reproduce this either, I tried to research the problem in a similar to what I did with #5221 but it's really hard to do that without being able to reproduce the problem.

**Comment by simonrozsival** [comment] 2019-10-07 11:51
This report sounds similar (even though it is Android):

```
User on Pixel 2  is saying that he cannot edit tasks if the app runs in the background.
BUG: Cannot edit any task after leaving it runs in the background for a long time (Android)

1. Open Toggl app
2. Left it runs in the background for a long time
3. Open task view and resume the app
4. Tap on any task
=> Edit mode of any task won't open
App name and version: Giskard/2.3.1
```

**Comment by simonrozsival** [comment] 2019-10-07 12:02
It kinda looks to me as if the DI container was deleted from memory, when the app was suspended by the OS and when the app is resumed, the DI container is not re-created correctly. I have no idea if it is possible though and how to reproduce it.

**Comment by pdrj** [comment] 2019-10-11 14:31
Possibly related: #5945 (as Simon mentioned above).

**Comment by Odrakir** [comment] 2019-10-28 14:54
I can't reproduce it. I think we have to keep an eye on this one, see if we manage to know the conditions under which it happens.

**Comment by heytherewill** [comment] 2019-11-12 14:01
I can't reproduce it, so I'm closing it for the time being

**Closed by heytherewill** 2019-11-12 14:01 UTC
Labels: crash, ios
