### ISSUE TITLE
iOS app keeps crashing in background

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6378] opened 2019-10-29 14:41 UTC
Using the latest TestFlight build of 2.5 (which was also released in AppStore), I was able to submit feedback into AppStore Connect whenever the app reported a crash over the weekend:

![image](https://user-images.githubusercontent.com/374616/67762760-7ccd6100-fa46-11e9-9f47-b94a7e34fdb3.png)

The problem is, that there is no crash report in AppCenter. We are now receiving analytics showing that BG sync finishes, so it does not (usually) crash during syncing. There's some other problem.

This issue is maybe a follow-up of #6039, but it might be unrelated to BG sync.

**Comment by amulware** [comment] 2019-12-20 14:02
Let's do another investigation. If we can't figure out what's happening (if anything), close this.

**Comment by juanlaube** [comment] 2020-01-14 11:37
This is still happening and seems to be happening only on the iPhone 7 🤔

**Comment by juanlaube** [comment] 2020-01-14 17:03
There's not enough information about these crashes, and I couldn't reproduce on the iPhone 7 simulator. I will remove myself from this issue for the moment.

**Comment by sofokli1** [comment] 2020-01-22 18:51
Since there is not much we can do about this, I am closing this for lack of info and reproducibility.

There is also a chance that we are not logging the crashes in appcenter due to the bug in the sync manager where it was not executing code if the stack trace was null and that includes the analytic call for sync failed. This bug was fixed https://github.com/toggl/mobileapp/pull/6928 and will be released in iOS 2.10. 

@amulware ➿

**Closed by sofokli1** 2020-01-22 18:51 UTC
Labels: crash, ios
