### ISSUE TITLE
Select workspace view crashes when default workspace isn't set

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#2782] opened 2018-07-31 15:15 UTC
## 🐛 Bug Report
When the user doesn't have a default workspace set, nothing in the workspace row in the settings is shown and pressing the row to select a workspace crashes the app.

## Expected behavior
After inspecting the code i found out that if there is no default workspace, then workspaces should be ordered alphabetically and then first one chosen as the active workspace. But that code isn't working properly for some reason.

## To reproduce
1. Create a few workspaces on the web app
3. Delete the default workspace on the web app
4. Log in with the mobile app.

**Comment by simonrozsival** [comment] 2018-08-02 13:48
I am not able to reproduce having no default workspace. When I leave the default workspace, I automatically get a different ws as the default one. Is there some trick how to do it?

**Comment by daividssilverio** [comment] 2018-08-02 21:53
There are two tricks to reproduce the state of "workspace-less":

1. With two accounts
Create two test accounts. `A` and `B`.
`A` creates 2 workspaces, `a1` and `a2`.
`A` invites `B` to both workspaces.
`B` accepts only the invite to `a1`.
`B` leaves its own default workspace.
`A` deletes `B` from workspace `a1`.

or

2. With three accounts (thanks @juanlaube )
`A` invites `C`
`B` invites `C`
`C` accepts `A`
`C` leaves `C`’s workspaces
`A` removes `C`
The invite from `B` is what keeps `C` alive

I Just realized this is not in question here. But the trick is there.

**Comment by daividssilverio** [comment] 2018-08-02 21:58
Actually, after becoming workspace-less from the steps above I was able to reproduce the state of having workspaces but without having a default workspace.

After becoming workspace-less:
1. Login on the web app.
2. You will be requested to create a new workspace.
3. Create one. (don't set it as default)
4. Create some more.
5. Logout and login on the mobile app.

**Comment by daividssilverio** [comment] 2018-08-02 21:58
But selecting a row the list won't crash giskard.

**Comment by simonrozsival** [comment] 2018-08-03 12:43
Well I think this issue is not related to being in no workspace, but rather having `null` as the default workspace. I came to the conclusion that I can set this manually in Realm studio.

**Comment by daividssilverio** [comment] 2018-08-03 18:15
So, the expected behaviour would be having the user `DefaultWorkspaceId` set to the result of `GetDefaultWorkspaceInteractor` when there's no `DefaultWorkspaceId` is null?

**Comment by simonrozsival** [comment] 2018-08-03 18:37
When the user has no workspace, then the code in the `PickDefaultWorkspace` method of the  `SettingsViewModel` will crash the app (null reference).

The question is: will the user be able to navigate around the app without any workspace in 1.9? I think that when there is no workspace, then we will show the user the view to create one, right? If the user cannot "postpone" creating a new workspace at that moment and go to settings, then I think that this is not a bug which would be possible in 1.9 (unlike in 1.8, when the user can have 0 workspaces in an extreme edge case).

**Comment by amulware** [comment] 2018-08-06 10:17
- We don't have to handle the no-workspace case, we'll soon be properly handling that by making the user create one, and until that things will crash
- But this issue talks about not having a default workspace, which is a case that for the time being can happen. We implemented a fallback for this to select an arbitrary workspace, to pretend we always have one. If that doesn't work right now, it should be fixed.

**Comment by amulware** [comment] 2018-08-06 10:19
Note that we don't actually want to change the user preferences, we just return an arbitrary workspace to make it not crash. There are issues that will make the user select a new default workspace, but we'll get to that later.

**Comment by simonrozsival** [comment] 2018-08-06 10:19
From my testing it seems that not having default workspace is not a problem. I cannot find a reason why it even should not work in the code.

The only reason for crashes is having no workspaces at all.

Can somebody else please test the behavior for a `null` default workspace in the `RealmUser` entity to confirm my findings?

**Comment by amulware** [comment] 2018-08-06 10:20
Ok, I see. Yes, if someone else can confirm what you said then this can be closed.

**Comment by simonrozsival** [comment] 2018-08-07 11:38
@arturs105 could you please be more specific about how to reproduce this?

**Comment by arturs105** [comment] 2018-08-07 11:41
Sure. First you need to get an account without workspaces. Do the thing with 2 accounts from [here](
https://github.com/toggl/mobileapp/issues/2782#issuecomment-410079411) (in the web app). Then log in the mobile app with the account that has no workspaces and you should be in the broken state.

**Comment by simonrozsival** [comment] 2018-08-07 11:43
OK, then we will solve this with the "no workspace" view and we can close this issue, @amulware.

**Closed** 2018-08-07 11:51 UTC
Labels: crash
