### ISSUE TITLE
Editing time entry, start time appears as UTC-0 (1.6)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2298] opened 2018-05-28 02:32 UTC
Click on an existing time entry.
Click to edit time
Click on the Start time
It is displaying in UTC-0
(Image shows untouched time wheel/barrel/selector)
![image](https://user-images.githubusercontent.com/18132080/40594537-eb383758-626e-11e8-9fda-54637eb76f50.png)

Wasn't this fixed in an earlier version?

**Comment by simonrozsival** [comment] 2018-05-28 06:17
This was supposed to be fixed by #2179

**Comment by amulware** [comment] 2018-05-28 06:31
I do not think that that commit was released with 1.6.

@ApocalypticFish Please be more specific, what do you mean with '1.6' in the title? Is this the current appstore build, or the nightly one? (in the latter case, version numbers are meaningless)

**Comment by vedr4n** [comment] 2018-05-31 06:46
@amulware This is happening with the latest AppStore version. It was just reported by a user in case /712065. I can also reproduce it on my phone. 

You should be able to reproduce it as well considering you're in UTC +1 (due of DST).

**Comment by sofokli1** [comment] 2018-06-12 20:16
@amulware Took a look into this but it seems that the issue is present in the AppStore version but not in `develop`. Apart from a maybe glitch (when selecting the start time the picker animates to the correct hour as it opens) I would close this issue.

**Comment by nicktoggl** [comment] 2018-06-13 06:31
/case/717740 video included

**Comment by amulware** [comment] 2018-06-13 07:07
Closing as probably fixed. Open new issue if this re-occurs in new releases.

**Closed by amulware** 2018-06-13 07:07 UTC
Labels: glitch, ios
