### ISSUE TITLE
RTL Languages Issue on Main Page

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4083] opened 2018-12-25 10:16 UTC
## ⛑️ User Support

This is related to #3494 

The user who reported the issue that was fixed in #3494 has reached out again to report alignment issues on the main (timer) page in the app. They shared a screenshot pointing out the issue, you can find it in the link below:

https://drive.google.com/open?id=1u29Im8X-7T1vM2RV94QZjR2q9HIs9uN5

The project name is aligned so far to the right that it's almost not visible

## About the user

App version: 1.9 (want to double check with the user, they were initially on Giskard/1.5.2 but have confirmed that the #3494 fix worked on the reports page so I assume he is on the latest version now)
Phone OS: 9 O_MR1
Phone model: Xiaomi Redmi Note 3

## Expected behaviour
The user should be able to see the full project name on the timer page for each TE (unless the project name is very long of course) 

## Update 14.08.2019

This issue now about https://github.com/toggl/mobileapp/issues/4083#issuecomment-458224149 - project names disappearing below the stop time fab.

**Comment by heytherewill** [comment] 2019-01-02 16:13
Possibly fixed by the yet-unreleased #4025

**Comment by juanlaube** [comment] 2019-01-21 17:24
#4025 didn't solve the problem for the text in suggestions

**Comment by pdrj** [comment] 2019-08-14 10:32
@juanlaube I can't find any issues with text in suggestions - do you mean suggestions when adding tags for a time entry for instance (that's where I was looking)? Has this maybe been fixed already?

I have a fix for the issue reported by @zdericnina, but I'd like @toggl/androids opinion on another problem I noticed. When project's title is long, the white to transparent gradient background we use around the fab makes the text a bit transparent as well. Have a look at the screenshots and please let me know if you think we should just use a white background there.

![long-white-gradient](https://user-images.githubusercontent.com/53510080/63014394-bacad800-be8e-11e9-9da0-cd602efde2df.png)
![long-white-bg](https://user-images.githubusercontent.com/53510080/63014408-c1594f80-be8e-11e9-9922-66842104336c.png)

**Comment by juanlaube** [comment] 2019-08-14 12:42
@pdrj looks like the problem with suggestions has been resolved. I don't remember (7 months! 😄) if that was for the suggestions in the main log or when starting a time entry, but both work fine now.

**Comment by heytherewill** [comment] 2019-08-14 12:55
> makes the text a bit transparent as well

This is by design, we fade out instead of using ellipsis or cutting the text abruptly. 

Given that the entire suggestions system was rewritten after this issue was created and that no one can find any problems with suggestions, I'm closing this issue. Thanks for the investigation, Piotr!

**Comment by pdrj** [comment] 2019-08-14 12:59
OK, this doesn't quite work for RTL locales though, but changing that would require more work (probably the best way would be to make the whole layout properly RTL).

@heytherewill  I don't think this should be closed, there is still the issue mentioned by @zdericnina for which I will prepare a PR, unless this has been somehow fixed in the meantime?

**Comment by heytherewill** [comment] 2019-08-14 13:13
Sure thing, but please update the issue description so it's clear what is being fixed :)

**Closed** 2019-08-14 14:07 UTC
Labels: android, glitch, up-for-grabs
