### ISSUE TITLE
Deletion not working after stress testing continue and deletion

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3328] opened 2018-10-03 10:38 UTC
## 🐛 Bug Report
I spammed continue and deletion on android by swiping left and right and the app stopped deleting entries and kept showing the deleted red bar on multiple entries.

It was possible to swipe any entry to the left after this to show the red deletion "banner" but after scrolling down and back up the entry remained and deletion wouldn't work until the app was restarted.

@daividssilverio  saw this happen

## Context
Spammed continue and deletion on Android 1.5.1

Build/Branch:1.5.1
Phone OS:8.0.0
Phone model:HTC U Ultra

## Expected behavior
Entries would be deleted

## To reproduce
Continue and delete entries in rapid succession

**Comment by heytherewill** [comment] 2018-12-19 14:49
I couldn't reproduce this. Can you guys? @daividssilverio @ApocalypticFish

**Comment by daividssilverio** [comment] 2019-01-18 12:55
I'll check to see if it's still happening later today. But when I did replicate that, I actually used multiple fingers to continue/delete time entries at the same time :) Not an usual usage of the app :)

**Comment by juanlaube** [comment] 2019-09-26 17:57
I couldn't reproduce the problem and the issue is from 20 versions versions ago, I think we should close this.

**Comment by daividssilverio** [comment] 2019-10-03 15:12
I'm not able to replicate it exactly the way it was.
What happens is that after a series of crazy fast deletions a bunch of time entries become unsyncable, and not able to be interacted with.

The steps to replicate the current and old behaviours are:
1. Get yourself a bunch of time entries
2. Disable grouped time entries
3. Using 4 or 5 of your fingers, swipe the most time entries to complete deletion the fastest you can.
4. Scroll down randomly and go back to step 3.

You should be able to get into a weird state, but not the original reported here.

**Comment by daividssilverio** [comment] 2019-10-03 15:13
By the way, I think this is an unreasonable usage of the app. Not sure if investing much time on fixing this is worth the time.

**Comment by pdrj** [comment] 2019-10-04 09:11
Thanks @daividssilverio. @amulware - are you good with closing this, based on the info provided in this thread?

I wanted to reproduce what @daividssilverio described, but my old phone doesn't seem to even let me swipe multiple entries at the same time.

**Closed** 2019-10-04 14:54 UTC
Labels: android, bug
