### ISSUE TITLE
Email entry field flashes when using 3D Touch cursor.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#292] opened 2017-07-19 09:52 UTC
Gif from iPhone 6s with iOS 11 public beta 2

![img_3026 trim](https://user-images.githubusercontent.com/15633003/28360732-0a87922a-6c7f-11e7-867b-72bde2da8a36.gif)

**Comment by simonrozsival** [comment] 2018-05-16 07:53
I think this is now "resolved" with the new login screen - I can't reproduce the issue there.

**Comment by willsb** [comment] 2018-05-29 20:42
@amulware Let's raise team morale by closing crazy old stuff 😄

**Comment by amulware** [comment] 2018-06-21 11:38
Team morale raised.

**Closed by amulware** 2018-06-21 11:38 UTC
Labels: glitch, ios
