### ISSUE TITLE
Syncing issue after switching between connections

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4955] opened 2019-04-19 10:28 UTC
## ⛑️ User Support

A user reported that if they are connected to a WiFi network while tracking time and switch to their carrier network at one point the app will have trouble syncing and manual sync will not help. 

Both Nina and I were able to reproduce this with version 1.20, you can find the steps below. 

## About the user

App version: Daneel/1.20
Phone OS: iOS 12.2
Phone model: iPhone X

## Expected behaviour
The app should be able to sync after users switch between networks. 

## To Reproduce

1. Start a timer while connected to a WiFi 
2. While the timer is running turn off WiFi to allow your phone to connect to your 3g/4g network
3. Stop the timer and the app will try syncing without success and you should end up with something like this:

![image](https://user-images.githubusercontent.com/36152180/56420517-865b5c80-629e-11e9-8154-146e2c75d84d.png)

NOTE: restarting the app helps, but the issue can be reproduced again after that.

**Comment by lise-toggl** [comment] 2019-05-09 06:06
This has also been reported by a user with S10+ ([case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/21886885017))

**Comment by dshr** [comment] 2019-05-21 16:04
Seems to be related to #5150 — we get the same connection timeouts as there.

**Comment by simonrozsival** [comment] 2019-05-23 08:03
I don't think it has something to do with the issue that @dshr linked. If there is a pending HTTP request which fails (because the connection to the server fails when user switches from wifi to cellular or the other way round or when he switches base stations while on the move), and it should display "Offline" (as is shown in the screenshot). But if the user pulls to refresh, it should all work. If not, and the only way to recover is restarting the app, then this is something we should look into.

@VeljkoTN can you check if the app is irrecoverably stuck after this happens?

**Comment by VeljkoTN** [comment] 2019-05-27 13:41
@simonrozsival yes it is, triggering a sync manually doesn't work, only restarting the app helps.

**Comment by dshr** [comment] 2019-06-06 09:12
After initially looking into the case I have discovered that we don't get repeated "offline mode" on the latest `develop` commit anymore, but any sync started after a connection change takes a quite while to actually return the "offline mode detected" message. This way, following the steps from the issue (start a TE, switch to TE, stop TE) would first result in an unsynced TE, then the first manual sync would return an offline mode message, and the next one would sync just fine. Still, this is quite bad UX.

My solution was to monitor network changes using [Connectivity from Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android) and stop any running syncs when we're swapping connections. This involved a lot of changes to the sync code, introducing a way to stop sync and, in the end, didn't help the issue at all 😅. As I found out, we trigger a push sync when we stop a TE already, so we actually get whole two failing syncs after a connection change.

I consulted Will, and he proposed that we go one level deeper, and instead of stopping sync we could stop HttpClient requests when we swap connections and send an appropriate exception down to the receiver.

**Comment by ApocalypticFish** [comment] 2019-06-08 13:23
conversations: 22359108284, 22360320770, 22362927989, 22330706982, 22369602442, 22370611348, 22372194045, 22373792095, 22374800013. pretty even mix of Android and iOS all within last 24 hours.

**Comment by heytherewill** [comment] 2019-06-27 18:46
I'm unable to reproduce this on my phone (Pixel 2) on current `develop` and I don't have an iOS device with cellular data to test this on. IMO, our app is resilient enough in this sense: The app will report as offline (as every other app does after the current connection was cut abruptly) and then after a while internet will return and everything will work normally. A reset is certainly not needed on Android (perhaps it is on iOS but I have no means of testing it atm).

I vote for closing this since it doesn't seem like there's much we can; we don't have control over how the OS handles switching connections and we're doing what we can with what information is provided to us

**Comment by amulware** [comment] 2019-06-28 06:25
On iOS, if I kill wifi during sync, it seems to be stuck syncing for about a minute before reporting offline. It would be better if it errored quickly.

Syncing again after that minute works however, so I can't reproduce the issue above either.

**Closed by amulware** 2019-06-28 06:25 UTC
Labels: api, bug, sync

**Comment by sofokli1** [comment] 2019-07-22 12:59
by following the steps of the issue i can reproduce but the problem is not permanent and it works with manual sync after 1 min or so

**Comment by sofokli1** [comment] 2019-07-22 13:00
this situation should be taken into account when the sync gets refactoring/update
