### ISSUE TITLE
Change the point at which we check for errors when editing dates/times

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5054] opened 2019-05-08 11:02 UTC
In the Wheel view, we are currently immediately preventing changes to start or stop time that would create a temporal inconsistency. 

This makes the editing process hard for some users who want to change the date of the start/stop time. The process requires them to change it in a specific order to avoid the temporal inconsistencies.

The [agreed solution](https://toggl.slack.com/archives/C029WU7AY/p1557293317039000) for this is to change the behavior so that the validation check is done only when attempting to save instead of immediately in the wheel view.

**Comment by amulware** [comment] 2019-05-08 11:05
Let's get this right and draw up some proper specs for exactly this is going to work.

Some notes:
- we'll probably want a small popup (ideally one that doesn't block interaction I figure) telling the user what's wrong (let's make sure we write clear error messages, and determine proper priority in case there is multiple things)
- we still don't wanna let people put end < start using the wheel itself I think

**Comment by amulware** [comment] 2019-05-08 11:07
Other ideas:
- use a shake animation, similar to what iOS has for wrong fields during signup (I don't think Android has these?) to indicate what data is bad
- already highlight and maybe even show error string inline when editing

**Comment by kornelijepetak** [comment] 2019-05-08 11:13
> we still don't wanna let people put end < start using the wheel itself I think
We need to allow that as well. Because the dates and times are set separately.
That's the core of the problem. Changing the date requires changing the time first, otherwise, the times will not work.

Honestly, I'd just relax all the forced validation and maybe just visually note that there's an inconsistency. Every forced change or prevention will cause issues in some scenarios.

**Comment by amulware** [comment] 2019-09-27 12:41
This is still a thing, and I figure it would be best if someone could take a look at what other apps do. Maybe also check how much user feedback there is on this, and what risks there might be by changing things.

**Comment by amulware** [comment] 2019-09-27 12:41
I'm tentatively scheduling it for someone to take a look and investigate, not for any actual implementation unless we can agree on something.

**Comment by semanticer** [comment] 2019-11-12 15:05
I guess the "needs-design" label is not entirely accurate since this issue needs some thought, research and maybe some UI sketch but we don't know yet if we need anything specific from our designers. I'm removing this label and prioritizing this in Android 2.8. Feel free to revert anything @amulware ➿

**Comment by arturs105** [comment] 2019-11-22 12:45
I though about this and came up with 2 potential solutions. Both of them are based on the error messages that we show in the edit time entry view (see screenshot at the bottom).

**Solution 1**

We show a similar error view at the top of the wheel view popup. We allow user to set whatever times and dates he/she wants, but after pressing save, we reveal the error view and tell them everything that they did wrong - duration too long, start time > end time etc.

**Solution 2**

Similar to solution 1, but we allow the user to close the wheel view popup view and show the error messages in the edit view instead. The same way we would show the description too long error.

In both solutions the time entry is marked as unsyncable until the user fixes it.

I, myself, am leaning more towards solution 2, since that one is more consistent with other errors that we show for invalid data. 🤔 Or maybe we could even show the error in both places... Anyways, this is for product to decide.

@maritoggl @amulware Your thoughts?

![IMG_9DFD73662FF1-1](https://user-images.githubusercontent.com/15633003/69426265-8be9bb00-0d35-11ea-8f86-a4a792807f45.jpeg)

**Comment by amulware** [comment] 2019-11-22 13:03
UI should never mark a TE as unsyncable - that's a state we get communicated by backend. If we allow the user to put broken data like that into our database, there's really no knowing what might happen. We might get crashes or other bugs all over the place.

I'm not sure if I care where we show this error, but I figure in the time selection screen makes the most sense? So the user can cancel those changes but not lose whatever else they did in the edit view? Also because there's no reason to let them back to the edit view if they'll have to get back to editing times anyways.

**Comment by kornelijepetak** [comment] 2019-11-25 06:55
I agree with the last @amulware's comment. If the problem is in the time, the error should not leave the time selection dialogue.

**Comment by maritoggl** [comment] 2019-11-25 09:08
Also agree with @amulware here.

**Comment by simonrozsival** [comment] 2019-11-25 09:30
If I understand this correctly, the proposal says that we would allow the user to change the start or end date independently, so that the view can be in a state when `end time < start time`.

I think that's OK. We would disable the confirmation button in this state and show some label with a short explanation.

The only problem I see with this is the wheel. What should happen to it when the end time is before the start time? Currently that's impossible to render. We assume that the start time comes first. In principle, I have two solutions for this: a) rewrite the wheel so it can display negative duration (I don't like this option) or b) disable (also make it semitransparent or even hide it) the wheel until the user fixes the invariant.

**Comment by kornelijepetak** [comment] 2019-11-25 09:40
Just a thought...
How hard is it to make it so that when you drag the END time on the wheel to be earlier than the START time and then release it that the start and stop are exchanged so that the value is reasonable?

**Comment by amulware** [comment] 2019-11-25 15:35
Kornelije's idea might be a solution, but I'd have to actually try it in the app to see how it feels. Otherwise, I'd say it shouldn't be too hard to make the wheel be able to render negative durations. Unless you overengineer it. :D

**Comment by amulware** [comment] 2019-11-25 15:36
Oh and if we make the wheel render negative durations, we can make the background colour of the time interval the same red colour as the background of the error message, which would be another visual clue you're doing something wrong.

**Comment by simonrozsival** [comment] 2019-11-25 15:40
> it shouldn't be too hard to make the wheel be able to render negative durations. Unless you overengineer it. :D

Displaying negative time duration sounds like overengineering to me 😄

**Comment by simonrozsival** [comment] 2019-11-27 10:29
I'd like to close this issue in order to move on with the 2.8 release. Did we agree on something? Is this something we really want to change at the moment? What should be the next steps to really figure out the new UX and the UI changes?

**Comment by maritoggl** [comment] 2019-11-27 12:59
I'm making an assumption that users that change their time using the time picker will also want to use the time picker to fix the issue instead of fixing the issue using the wheel. For that reason, I'd go with hiding the wheel and displaying an error until the issue is fixed. We'll see what the user feedback will be - if we need to improve the wheel behavior in the future, we'll do so, but we don't need to overcomplicate things straight away. 
I did consider recommending simply disabling the wheel as well (instead of hiding it), but then we'd still need to tackle the question about how should the disabled wheel look like etc. Wheel with 0:00:00 duration already looks pretty disabled, so it might just confuse users if nothing happens when they try to interact with the wheel. So let's keep things simple instead.

**Comment by simonrozsival** [comment] 2019-11-27 13:15
OK. I'll create a follow-up issue with the specs.

**Comment by simonrozsival** [comment] 2019-11-27 13:27
I'm closing this issue now in favor of the follow-up issues.

**Closed by simonrozsival** 2019-11-27 13:27 UTC
Labels: android, ios
