### ISSUE TITLE
Reports: there is no placeholder for the charts when there is no time entries on the period

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2080] opened 2018-05-09 20:15 UTC
I've tested on the emulator and a Nexus 5.

<img src="https://user-images.githubusercontent.com/2173493/39837156-9916a7d6-53a3-11e8-9019-d9901b33beb5.png" width="240">

**Comment by willsb** [comment] 2018-05-10 08:00
Duplicate of #1624

**Closed by willsb** 2018-05-10 08:00 UTC
Labels: android
