### ISSUE TITLE
It's possible to scroll the week controller to a week without enabled days

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6341] opened 2019-10-25 15:58 UTC
Same thing happened on android: https://github.com/toggl/mobileapp/pull/6163#pullrequestreview-304582396

Noticed while testing #6340

**Comment by arturs105** [comment] 2019-10-28 12:41
Could you elaborate on this? What was the beginning of week set to and what was the current date?

**Comment by daividssilverio** [comment] 2019-10-28 12:48
Of course. All you have to do is to set the beginning of the week to the next weekday from today. For example: For today, Monday, set the beginning of the week to Tuesday.

**Comment by arturs105** [comment] 2019-10-29 12:06
I just tried all possible beginning of week settings and couldn't reproduce the problem.

**Comment by sofokli1** [comment] 2019-11-12 14:32
@daividssilverio if you can't reproduce this, we can close this

**Comment by daividssilverio** [comment] 2019-11-18 19:42
Hey @arturs105 I managed to replicate it, here's how it looks:

Today being "Monday", all I did was to set the `First day of the week` in the settings to "Tuesday".
The selected day in the calendar was today when I did it. After changing the first day of the week, you can try swiping the week stripe header twice and you should get into this view state:

![image](https://user-images.githubusercontent.com/2173493/69083931-7c0e6600-0a19-11ea-8047-e307e294b555.png)

**Comment by juanlaube** [comment] 2019-12-17 17:47
I couldn't reproduce this.

**Comment by dshr** [comment] 2019-12-26 11:24
Can't reproduce this either. Closing.

**Comment by daividssilverio** [comment] 2019-12-30 15:28
Consider reopening this. I'll post a video internally executing the steps to replicate it.
This might be happening only on simulators though.

**Comment by dshr** [comment] 2019-12-30 19:16
Reopening this in light of new info — the "unwanted" scrolling is not forward in time, but backwards.

**Comment by sofokli1** [comment] 2020-01-21 18:31
Closing it a gain because me and @daividssilverio can't reproduce. @dshr if you can reproduce please reopen the issue. For reference a video of the issue from @daividssilverio when it was possible to reproduce this very edge case.
![Jan-21-2020 20-25-05](https://user-images.githubusercontent.com/885122/72832074-c8318d00-3c8c-11ea-89d3-8489f4f892de.gif)

**Closed by sofokli1** 2020-01-21 18:31 UTC
Labels: bug, ios
