### ISSUE TITLE
Onboarding settings not resetting ever

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#2767] opened 2018-07-30 09:52 UTC
We are not resetting the Onboarding settings. The `Reset()` method on `SettingsStorage` is not ever called. 

This causes that a second signup from the same phone doesn't see the on boarding. And potentially other issues too.

**Comment by amulware** [comment] 2018-07-30 09:57
This is currently by design. Ref https://github.com/toggl/mobileapp/issues/1969

**Comment by amulware** [comment] 2018-07-30 10:00
Closed as pretty much duplicate.

**Closed** 2018-07-30 10:00 UTC
