### ISSUE TITLE
What happened to the AppDidEnterForeground event?

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6072] opened 2019-10-09 10:40 UTC
I noticed that before September 17 or so, this event was reported roughly once per session, since then it’s roughly twice. Does this even make sense? Shouldn’t it be EXACTLY once per session? (How are sessions defined exactly?) Did we change some code that makes us accidentally report the event twice?

<img width="378" alt="AppDidEnterForeground · Toggl Android · App Center" src="https://user-images.githubusercontent.com/3987892/66474756-da930c80-ea89-11e9-920b-242952702499.png">

**Comment by amulware** [comment] 2019-10-09 10:43
Actually.. I’m seeing the same pattern on almost all events on Android! This is not good at all.

**Comment by semanticer** [comment] 2019-10-24 19:54
This happened in clear correlation to the release of 2.3(.1)

**Comment by semanticer** [comment] 2019-10-25 11:58
The total count of events looks fine, so there must be a problem in how we count the sessions ( or if Microsoft changed something ? ...)

**Comment by semanticer** [comment] 2019-10-25 13:01
To answer what a session really is according to Microsoft:

> A session is defined as the time from the app coming to foreground to the last event before going to the background. If no custom events are identified within 5 minutes in a session, the session will not be counted.
https://docs.microsoft.com/en-us/appcenter/analytics/overview

**Comment by semanticer** [comment] 2019-10-25 14:35
Some candidates that might be responsible for this: 
- https://github.com/toggl/mobileapp/commit/359e131d078af4a315a9fef455ed2712bc015363
- https://github.com/toggl/mobileapp/commit/3ecdf76b2002e6f4154f297a62ff5beff3a84d9f
But I need to find a good way to debug Analytics to know more.
Also, it looks like we are now closer to the numbers on iOS, so we might be both wrong or both correct now :-)

**Comment by semanticer** [comment] 2019-11-06 14:17
I don't have proof yet but it looks like we are now counting the sessions correctly. I compared the sessions count on iOS vs Android: 

**Android**
<img width="514" alt="Screenshot 2019-11-06 at 14 15 33" src="https://user-images.githubusercontent.com/535613/68301930-4b394300-00a1-11ea-98d9-969258d7b999.png">

**iOS**
<img width="502" alt="Screenshot 2019-11-06 at 14 28 35" src="https://user-images.githubusercontent.com/535613/68302166-c0a51380-00a1-11ea-9ede-38336f9fa6a4.png">

So if you compare those two graphs it's pretty clear we are now closer to what we have on iOS (and hopefully closer to reality) 

@daividssilverio it might take a lot more time to pinpoint where exactly this change happened, should I continue researching this? Or should I move to something more important now?

**Comment by daividssilverio** [comment] 2019-11-06 15:09
Hey @semanticer I think you can start looking at something more important than this, unless @amulware says something else.

Btw, @amulware is talking about `count per session`, you showed us `daily sessions per user`.

The source of the increases in `avg. count per sessions` for the `AppDigEnterForeground`. In 2.3 we've added the android lifecycle components to track the `OnStart` and `OnStop` lifecycle events of our application which is more accurate than the previously used method of figuring out if the app was in foreground using Activity's lifecycles.

The problem is that we are triggering multiple `AppDigEnterForeground` events in a single AppCenter session. Depending on how AppCenter implements a session internally, we might be counting it twice and I'm not sure if we should do something about it.
On android, the event will be triggered every time the app comes to foreground, that includes:
- The user presses the "recents" button and came back to the app very quickly
- The apps launches an external intent (browser screens)
- When the screen is turned off by the system after 10 secs (user defined) and comes back to the same app
- Others I'm not aware.

We can ask AppCenter devs/support for more details on that if we really want to go further investigating this.

Definition of the AppCenter user session https://docs.microsoft.com/en-us/appcenter/analytics/overview
>A session is defined as the time from the app coming to foreground to the last event before going to the background. If no custom events are identified within 5 minutes in a session, the session will not be counted.

**Comment by amulware** [comment] 2019-11-06 15:21
Please note my other comment above. It's not just this single event.

<img width="393" alt="1338E45F-5283-4FEE-BF4F-C0D732A4D553" src="https://user-images.githubusercontent.com/3987892/68311071-ed105e00-00a8-11ea-903f-6d89c53a58b8.png">

Something change with our analytics.

**Comment by semanticer** [comment] 2019-11-06 15:21
`count per session` increased almost for every event as @amulware mentioned. The total count of these events stayed the same so the sudden change in `count per session` is clearly caused by the drop in `daily sessions per user` - both events also occurred at the same time during 2.3(.1) rollout.

**Comment by semanticer** [comment] 2019-11-06 15:28
So in short - it looks like we have the same consistent metrics on both platforms now but I have no idea if they are both wrong or both correct.

**Comment by daividssilverio** [comment] 2019-11-06 15:42
Ok, something clearly happened, I didn't read all of the comments in the issue before.
Then maybe another fresh pair or eyes could do some good, what do you think @semanticer ?

**Comment by daividssilverio** [comment] 2019-11-06 17:09
Quickly looking at https://github.com/toggl/mobileapp/compare/android-2.2.1...android-2.3.1
and specially at @semanticer suggested commits. I also can't see anything that would cause duplicated/increased events.

**Comment by semanticer** [comment] 2019-11-06 22:57
There is also a small chance Microsoft changed something on their side.

**Comment by semanticer** [comment] 2019-11-11 13:01
@amulware @daividssilverio should we spent more time on this, or should someone else take a look? I'm still more or less convinced we now have a correct representation of reality :D

**Comment by daividssilverio** [comment] 2019-11-11 14:02
Hey, I've started a chat with the `AppCenter` support team just in case. I'll update this issue as I clarify things with them. This won't be ready for 2.7 anymore. Is it ok to move it to 2.8 @semanticer ?

**Comment by semanticer** [comment] 2019-11-11 14:04
Sure, let's give it a few more days in 2.8
➿ @amulware

**Comment by semanticer** [comment] 2019-11-27 23:16
I believe @daividssilverio reached out to Microsoft and they did not find any issue with our stats on their side. We can look at this tomorrow/today for the last time.

@amulware ➿

**Comment by daividssilverio** [comment] 2019-11-28 12:17
While I had some trouble making the logs because of the AppCenter Adhoc secret-keys, the guys app center said they didn't see anything wrong. It might be worth figuring out the "right way" of collecting and sending the logs to get support from AppCenter and re-open the ticket I've started.

![image](https://user-images.githubusercontent.com/2173493/69805547-460a7800-11b7-11ea-9505-3b24dfd86ad4.png)

**Comment by amulware** [comment] 2019-11-28 16:18
I'm fine closing this for now. I agree it _looks_ like the data is probably fine now (and was broken before for.. reasons). We can keep this in mind for when we do another review of our analytics.

**Comment by semanticer** [comment] 2019-11-28 18:01
I turned on logging and tried to find some difference between now and then but without success. I also went through all events but haven't found any pattern there.  So I'm closing this for now.

**Closed by semanticer** 2019-11-28 18:01 UTC
Labels: android, bug, metrics
