### ISSUE TITLE
UI doesn't update when creating project into non-default WS

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1088] opened 2017-12-04 13:26 UTC
*I used test.account.2 to test that.*

1) Start a new TE
2) Tap @'add some text here' eg @testingprojectabc
3) Tap "+ Create project 'testingprojectabc'"
4) Project creation view opens: Tap on a WS field and change the WS to non-default one. (By default was selected 'AutoShop' and I changed it to 'Big Company Workspace')
5) Tap 'Create'
6) App directed me back to TE creation view where I saw plain text/description: '@testingprojectabc' and no token.
7) Tap green checkmark: Project is created in the DB (checked from the webapp) but mobile UI didn't update.

**Comment by willsb** [comment] 2017-12-04 13:33
Duplicate of #1024

**Closed** 2017-12-06 22:02 UTC
Labels: critical, pending-review
