### ISSUE TITLE
App crashes when starting a TE without description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#742] opened 2017-10-17 19:53 UTC
> If I start entry without description, dismiss it via "green checkmark" down, and go back to the editing - app always crashes. If i try that after the start again it works. Stopping & starting new one and repeating this is sure way to kill it again

I managed to reproduce only with connection. Without wifi/data, it didn't crash.

**Comment by amulware** [comment] 2017-10-20 09:28
Duplicate of #759

**Closed by amulware** 2017-10-20 09:28 UTC
Labels: bug
